### ISSUE TITLE
Add basic plugin functionality

### ISSUE THREAD

**Issue by dignifiedquire** [pegjs/pegjs#106]
This is the issue for creating the proposed plugin system discussed in #100.

**Comment by mnpenner** [comment]
Is this plugin API documented anywhere? I want to use a plugin to inject an "initializer".

**Comment by ming-codes** [comment]
I'm looking for that plugin API doc too :(

**Comment by futagoza** [comment]
The plugin modules have to export an object, with one function named `use`:
```js
export function use( config, options ) {
    const { parser, passes } = config;
    // your code, no return...
}
```
The plugins can modify `config` and `options`, which means they can change the parser, add or remove passes and change the `options` that will get passed to the compiler.
