### ISSUE TITLE
The ability to access a rule from within another rule's action and dynamically add new rules

### ISSUE THREAD

**Issue by fresheneesz** [pegjs/pegjs#144]
The ability to access a rule from within another rule's action would have similar benefits as making anything first class - your rules would be first class and could be manipulated in much more interesting ways. In Lima (my programming language), the user is allowed to create and pass around "custom functions" as first class constructs. These are values which can arbitrarily consume the characters in front of it until it decides its done. For example:

```
var x = realCustom characters:
   ;; parse (some of) the characters and execute something
   ;; the remaining characters will be returned
   ;;   to the parent parser (probably the main parser)

var f = fn custom: ;; normal function
  custom abcdef ;; lets say x just parses 6 characters

f[x~] ;; the tilde (~) tells x to not parse anything (yet) 
        ;;   but be passed as a value
```

Because of this functionality, I need a parser that can add rules on the fly as it parse a document. 

Another reason to have this kind of functionality is to bring the full power of the parent language into the parser. First class rules could be be passed into other rules to give the parser an elegance on par with languages with first class functions (if PEG.js had parametric rules: https://github.com/dmajda/pegjs/issues/45 ).

**Comment by dmajda** [comment]
I decided I won’t implement this.
