### ISSUE TITLE
Warn about unused rules

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#200]
Unused rules should be reported as warnings. This is dependent on implementing a warning mechanism.

See also #193, where a pass is added to report unused rules as an error.

**Comment by futagoza** [comment]
This is currently implemented as an error, but as David mentioned, after implementing a warning system, this should be reported as a warning and not an error.

**Comment by polkovnikov-ph** [comment]
...especially since there could be several exported rules.

**Comment by futagoza** [comment]
@polkovnikov-ph That's exactly what I was thinking when planning Stage 1 of #523

**Comment by futagoza** [comment]
I implemented this in 6500189, with the pass based on what @Mingun did in [a commit on Mingun/pegjs](https://github.com/Mingun/pegjs/commit/165c14d1cfd702048e42b9f01699dc93c016df86#diff-f813da125f0cfc7a5ccde494660c1abb) and the tests based on @vrana's #193
