### ISSUE TITLE
report-left-recursion.js performance is suboptimal

### ISSUE THREAD

**Issue by palant** [pegjs/pegjs#203]
`report-left-recursion.js` currently takes around 40 seconds to check my grammar. This time can easily be halved by always using the same `appliedRules` array instead of creating new ones all the time:

         rule:
           function(node, appliedRules) {
    -        check(node.expression, appliedRules.concat(node.name));
    +        appliedRules.push(node.name);
    +        check(node.expression, appliedRules);
    +        appliedRules.pop();
           },

Some more performance can be gained by building a lookup table for rules instead of searching through `ast.rules` every time:

        var rulesByName = {};
        for (var i = 0; i < ast.rules.length; i++)
          rulesByName[ast.rules[i].name] = ast.rules[i];

Doing this before the check starts allows replacing the slow `utils.findRuleByName(ast, node.name)` call by `rulesByName[node.name]`.

**Comment by dmajda** [comment]
I [solved](https://github.com/pegjs/pegjs/commit/cdeecf750f8a3f781459ed817815a537392993c1) the array copying part. With linear search for rules I’ll wait until someone brings it up as a problem with a real-world grammar.
