### ISSUE TITLE
Add support for left recursion

### ISSUE THREAD

**Issue by yang** [pegjs/pegjs#231]
Via a modification to basic Packrat memoization as detailed in http://www.vpri.org/pdf/tr2007002_packrat.pdf.  This is implemented in Scala 2.8.0's parser combinators.  Would be very handy to have for dealing with many avoidable refactorings, allowing for more readable/maintainable grammars.

**Comment by batiste** [comment]
Hi,

After some research in PEG.js and Jison I came across this thread. I really wanted left recursion to work for my project so I implemented a Grammar Parser using the paper mentioned by @yang in the original post. The result is rather simple and seems to work reasonably well:

https://github.com/batiste/EPEG.js

Any comments or feedback is welcome.
Cheers

**Comment by yang** [comment]
@batiste Nice!  Does EPEG.js do anything special to deal with the issue highlighted by the @dmajda above (https://news.ycombinator.com/item?id=1198967) / does it implement the Medeiros algorithm pointed out by @GerHobbelt?  Just curious, thanks.

**Comment by batiste** [comment]
@yang @dmajda might be right. But I have to say I haven't  implemented the last part of the paper that describe what they call "indirect left recursion" as it became too complicated for me. I have written a test that highlight the issue:

https://github.com/batiste/EPEG.js/blob/master/tests/tests.js#L388

The last 2 tests don't pass:

     assertComplete("baba", gram10);
     assertComplete("abab", gram10);

I haven't needed this in my current project but my ambition is still to have left indirect recursion working. For that I think I will probably need to have a good look at the Medeiros algorithm described by @pjeby
