### ISSUE TITLE
One line grammar that crashes PEG.js parser

### ISSUE THREAD

**Issue by Artazor** [pegjs/pegjs#232]
`s={expected("}")}`

Expected: Generated Parser
Observerd: Parser generation failed with error: `Line 1, column 15: Expected "/", ";", end of input or identifier but "\"" found.`

btw, `s={expected(")")}` - generates parser successfully

**Comment by Mingun** [comment]
I want to note that now the grammar of PEGjs contains things, specific to JS, namely, labels are forbidden to have names, as at the reserved JS identifiers. It also is part of a lexer. Therefore, for consistency, it is worth or deleting such restriction, or to add the partial lexical scan for actions (I prefer the first candidate solution).

Actually, it is possible not to delete, and to improve the current behavior, having made the rule `ReservedWord` set up through options:
```pegjs
ReservedWord = name:IdentifierName &{ return exists(options.reserved, name); }
```
But as the rule ReservedWord is used only in the rule Identifier, such final decision is reasonable: remove `ReservedWord` and all rules, that it referenced, completely and change Identifier to
```pegjs
Identifier
  = name:IdentifierName !{ return exists(options.reserved, name); } { return name; }
```
