### ISSUE TITLE
parse async

### ISSUE THREAD

**Issue by andreineculau** [pegjs/pegjs#273]
Based on https://groups.google.com/forum/#!topic/pegjs/dL6HbQAC9Y0
I was thinking about an .abort() helper
which implies making .buildParser and .parse async

**Comment by dmajda** [comment]
I don’t plan implementing async/interruptible parsing for at least next few months. However, if someone more interested than me tackles that as a plugin I’ll be really happy. It would be a great way to explore the API and issues without doing experiments in PEG.js mainline.

With the current bytecode-based architecture, the plugin should need just to replace the `generateJavascritpt` pass with its own.

Closing this issue.
