### ISSUE TITLE
chained rules

### ISSUE THREAD

**Issue by andreineculau** [pegjs/pegjs#276]
Disclaimer: I don't know if re-defining rules is "wrong" from a grammar/PEG/@dmajda perspective, but it works, and I'm using that in my favour (to re-use grammars).

I discovered that PEGjs is probably doing some optimization down the line, which can end up with broken matches, see http://peg.arcanis.fr/14Ql4P/

```
start
  = start2
  
start2
  = start3

start3
  = "a"

start2
  = "b"
```

is basically saying that start should match 1 "b", because start2 is getting re-defined.

But it won't. It will expect 1 "a"

**Comment by dmajda** [comment]
Redefining rules is not officially supported. This bug will disappear when #318 is fixed.
