### ISSUE TITLE
Provide more context in Syntax Error messages

### ISSUE THREAD

**Issue by igravious** [pegjs/pegjs#279]
If many rules start with the same literal expression it can be difficult to understand where the generated parser encountered syntax in its parse tree.

Imagine the rules:
````
ONE "one" = FOO BAR
TWO "two" = FOO BAZ
FOO "foo" = "/"
BAR "bar" = "r"
BAZ "baz" = "z"
````

````
{ message: 'Expected foo but end of input found.',
  expected: 
   [ { type: 'other', description: 'foo' } ],
  found: null,
  offset: nn,
  line: x,
  column: y,
  name: 'SyntaxError' }
````

It would be nice if the generated parser provided the rule as context in the message if this is at all possible, like so: `rule: 'one'`

**Comment by Mingun** [comment]
I implement part of this in #225

**Comment by dmajda** [comment]
Judging by the example you want to see some parent rule of the rule whose description ends up in the message in the `rule` property. But how would you decide what rule to put there in case like this?

```
a = b
b = c
c = d
d "d" = "d"
```

Here the message will talk about `d`, but one could put any of `a`, `b`, `c` into `rule`.

Also, do you want this just for debugging, or for something user-facing?

**Comment by dmajda** [comment]
No answers from the reporter, closing.
