### ISSUE TITLE
Improve plugin error messages: Expose source line and column numbers

### ISSUE THREAD

**Issue by lydell** [pegjs/pegjs#280]
Here is an example. A coffee-script plugin is used to be able to write actions in coffee-script.

```
Foo
  = "foo" { @foo text( }
```

As you can see above, the ending `(` is forgotten above. All the plugin knows is that the error occurred at line 1, column 10 of that coffee-script snippet. Imagine the above example being a part of a large file. It will be difficult to find.

It would be really nice if the .pegjs parser saved the source line and column on each of its AST nodes. Regardless of plugin, this would allow for better error messages.

This is really easy to implement: Just add a new helper function in the initializer:

```js
function loc(node) {
  node.location = {
    line: line(),
    column: column(),
    offset: offset()
  };
  return node;
}
```

Then wrap each returned `{type: ..., ...}` object in `loc()`.

Would you accept a PR for this?

I found the need for this when working on <https://github.com/michaelficarra/CoffeeScriptRedux/pull/321>.

**Comment by dmajda** [comment]
This [got recently fixed](https://github.com/pegjs/pegjs/commit/89146915ce7e3f593fce96d217c06f287fc15bab) as a side effect on adding location information to error messages thrown by `PEG.buildParser`. Closing.

**Comment by lydell** [comment]
Cool, thanks!

**Comment by yanickrochon** [comment]
I had to look at this issue to understand how do use the "`location`" function as described in the README. Please update :)

**Comment by dmajda** [comment]
@yanickrochon Feel free to submit a PR with suggested changes.
