### ISSUE TITLE
"Parsers can also support their own custom options"

### ISSUE THREAD

**Issue by AllThatIsTheCase** [pegjs/pegjs#284]
The documentation says that parsers can also support their own custom options. How do I enable this? I'm generating the parser from the commandline, and I'm using the generated code. I'd like to pass context to the "parse" function.

**Comment by dmajda** [comment]
> I'd like to pass context to the "parse" function.

You can do it when you invoke it:

```
parser.parse(input, { customOption: "abcd" });
```

Inside the parser code you can then access passed options using the `options` variable.

Next time, please ask questions in the [Google Group](https://groups.google.com/forum/#!forum/pegjs), the issues are for reporting bugs and requesting new features.
