### ISSUE TITLE
JSHint feedback

### ISSUE THREAD

**Issue by AllThatIsTheCase** [pegjs/pegjs#291]
The generated parser produces jshint warnings that could be interesting to address; all relate to the use of '==' and '!=' rather than '===' and '!=='

**Comment by dmajda** [comment]
You do not state which parser you have in mind. However there is currently not a single instance of `==` and `!=` in the code generator and the PEG.js codebase (including the generated PEG.js grammar parser) also passes a JSHint check with [`eqeqeq`](http://jshint.com/docs/options/#eqeqeq) set to true. This means any `==` or `!=` in the parser must come from user code.

Closing as invalid.
