### ISSUE TITLE
Is there a way to translate error messages?

### ISSUE THREAD

**Issue by meglio** [pegjs/pegjs#293]
Hello.

We're using PEG.js in an internationalized web application. Is there a way to pass in options to customize error messages? If not, is it planned and what's the best way to achieve the goal?

Many thanks.

**Comment by dmajda** [comment]
The `SyntaxError` exception thrown by a generated parser contains all the data needed for building your own error message (in the `expected` and `found` properties). Have a look at the [`buildMessage`](https://github.com/pegjs/pegjs/blob/eaca5f0acf97b66ef141fed84aa95d4e72e33757/lib/compiler/passes/generate-javascript.js#L1075-L1119) function to see how parser itself does it.

One small caveat is that the expectations can contain two English strings as their description: “any character” and “end of input”. This can be trivially handled using a small translation table without any support on PEG.js side.

Having a direct translation support on PEG.js side would be nice, but given the use case is solvable in reasonable way (as described above) and there is very little demand for this feature I’m closing this issue.
