### ISSUE TITLE
New prefixed types

### ISSUE THREAD

**Issue by andreineculau** [pegjs/pegjs#297]
After https://github.com/dmajda/pegjs/issues/36#issuecomment-58744149, two new types would add functionality to PEGjs.

Both `&{ }` and `!{ }` match, but do not advance the parser position. For expression this is possible by simply doing `&expression expression`, but it's impossible for predicates (since predicates may have unknown length).

The top-of-mind suggestion is to add `&&{ }` and `!!{ }` (it might become very easy to make typos) so that it is possible to have

```
{ var foo = function() {return "foo" /*meaning string with unknown length*/ } }
rule1 = foo:&&{ return foo() } "barbazfoo" { return foo }
rule2 = "foo" barbaz:!!{ return foo() }+ "foo" { return barbaz }
```

**Comment by dmajda** [comment]
I’m not going to add this. If anything, this use case should be handled by a generic construct to match a JavaScript expression in combination with simple (non-semantic) predicates.
