### ISSUE TITLE
AST generated by PegJS Grammar is not valid JSON

### ISSUE THREAD

**Issue by ab34** [pegjs/pegjs#309]
Steps to reproduce:

- Generating an AST from the source PEGJS Grammar via itself (the source PEGJS Grammar).

- Parsing the generated AST with the JSON PEGJS Grammar.

The result is not valid JSON.

(Via the online parser)

**Comment by dmajda** [comment]
This issue really belongs to the [website repo](https://github.com/pegjs/website).

The online demo uses [jsDump](http://flesler.blogspot.cz/2008/05/jsdump-pretty-dump-of-any-javascript.html) to display output. This library may not always produce a valid JSON, but it processes objects like dates, regexps, and functions [nicely](http://demos.flesler.com/jsDump/), whcich could be handy. I’m not religious about using it, so if you feel something else would make more sense (be is simple `JSON.stringify` or something else), please file an issue or a pull request at the [website repo](https://github.com/pegjs/website).

With that, I’m closing this issue.
