### ISSUE TITLE
Parser doesn't recover if optional token steals match from a required token.

### ISSUE THREAD

**Issue by DigiTec** [pegjs/pegjs#310]
Note, I haven't fully debugged this and there are many workarounds that I have found to get around the bug. However, it would be interesting to understand why it fails to match and what might be wrong in the backtracking behavior.

Note the parser in this case isn't very strong because of its use of _, its only to demonstrate the issue. By making mods and type more specific and by requiring trailing [ ]+ instead of [ ]* between tokens then things work out a lot better and the parser works.

/*
Input
final LatLng(

Expected:
mods resolves 'final'
_ resolves space
type? resolves LatLng then fails then _ and fails ident
type? advances then _ resolves nothing ident resolves LatLng...
 */

start = mods _ type? _ ident _ '('

mods = 'public'? _ 'private'? _ 'final'?

type = IDENT

ident = IDENT

IDENT = [A-Za-z_]+

_ = [ ]*

**Comment by Mingun** [comment]
Rule `ident` fail to match, because at this monent cursor at symbol `(`, but `ident` must contain only `[A-Za-z_]` at least one times. Then parser backtrace, and, as no other alternatives found, parse fail.

**Comment by dmajda** [comment]
@DigiTec The `?` oeprator doesn’t backtrack. This means the failure of `ident` to match doesn’t magically cause `type?` (which already matched `LatLng`) to match nothing and retry. This is not a bug, this is by design.

The grammar can be easily fixed e.g. like this:

    start = mods _ type _ ident _ '('
          / mods _ ident _ '('

@Mingun Please avoid unnecessary statements like your last one. Thanks.

**Comment by Mingun** [comment]
> @Mingun Please avoid unnecessary statements like your last one. Thanks.
But, what's wrong? I don't know English so well to write but I know enough to understand technical texts. If my last sentence seemed offensive or something similar, I apologize. I didn't want anybody to offend at all. I write as I can :)

**Comment by DigiTec** [comment]
No offense taken. I was distilling a report from someone else who is less familiar with grammar productions and just wondered why it wouldn't work. As noted, I had many workarounds to provide them that made the grammar stronger. It makes sense that I would be responsible for disambiguating the grammar for the optional token in retrospect.

**Comment by dmajda** [comment]
@Mingun Criticize ideas, criticize code, but don’t criticize the person behind them. He/she may get offended and the resulting discussion often becomes all but productive.

You’ll find rule similar to this in pretty much any netiquette guide.

**Comment by lonniev** [comment]
I just fell into this trap. I thought P Q? R meant that either of P Q  R or P R were acceptable. (As it would be for regex and -- unless I've forgetten something -- antlr.)

What is the usecase for expression ? if not to simplify the longer form?

@Mingun can question my understanding of PEG without insulting me.

**Comment by lonniev** [comment]
Ah, for me, P Q? R works as expected. However, I had a case of:

rule =
          T
        \ T B
        \ B

in addition to the use of some term? expressions.

My error was because subrule T came before subrule T B. When I rewrote the rule with T B first, it matched all 3 cases. Order matters.
