### ISSUE TITLE
Online PEG fails when returning an object with a length key from a rule.

### ISSUE THREAD

**Issue by ZiCog** [pegjs/pegjs#313]
I am trying to parse a comma separated list of integers into a JSON object containing keys that name those integer values.

So this: "1,2,32"

Becomes this:

    {
        "animalprops": {
            "height": 1,
            "length": 2,
            "teeth": 30
        }
    } 

And this is the grammar I use:

    start
      = p:animalprops
      {
         return {animalprops: p} 
      }
    animalprops
      = i1:integer "," i2:integer "," i3:integer
      {
        return {
          height: i1,
          length:  i2,         /* FAIL */
          teeth:  i3
        };
      }
    integer "integer"
      = digits:[0-9]+ { return parseInt(digits.join(""), 10); }

Problem is that in the online PEG the output of the generated parser is:

    {
        "animalprops": [
            undefined,
            undefined
        ]
    }

Clearly the object I am trying to return is somewhere being treated as an array and the array length is being set to 2. Changing the input to "1,4,32" for example will result in 4 lines of "undefined" in the output.

The generated parser does not have this problem when used in my node.js test program.

Fault seen in FireFox 34.0.5 and Chrome 35.0.1916.153 on Debian Wheezy

**Comment by Mingun** [comment]
It is a [bug][1] in external library `jsDump` which the site uses for a result output. So you can be quiet :)
[1]: pegjs/website#5

**Comment by ZiCog** [comment]
Oops sorry, yes, I didn't realize there was a separate website repo with issues of it own.
Should I raise this issue over there now or are we OK ?

OK. I'll sit at the back an be quite :)

**Comment by dmajda** [comment]
> Should I raise this issue over there now or are we OK ?

As @Mingun pointed out, the bug is already [tracked](https://github.com/pegjs/website/issues/5). I’ll gladly accept a patch in the form of replacing jsDump with a fixed version/fork or some different library.

Closing here.
