### ISSUE TITLE
Make labels behave like block-scoped variables

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#316]
Labels should basically work like block-scoped variables, where “blocks” are created implicitly by `/`, `&`, `!`, `?`, `*`, `+`, `$`, sequences, labels and actions. This means that:
  * Actions should see all labels defined at the top level of the preceding expression or sequence *and* labels defined on levels above them.
  * Predicates should see all labels defined at the top level of the sequence they are embedded in that precede the predicate *and* labels defined on levels above them.

For example, parser created from the following grammar throws `a is not defined` error today, but it will return `["a", "a"]` once this issue is fixed:

```
start = a:"a" ("b" "c" { return a; })
```

Split off from #69.

Related pull request: #180

**Comment by andreineculau** [comment]
I should check it out myself, but does this mean that it works the same between different rules?

```
start= a:"a" b {return [a,b]}
b = b:"b"
```

**Comment by dmajda** [comment]
Label scope is of course limited to expressions in one rule. Anything else would be madness (think recursion).
