### ISSUE TITLE
action not run sometimes

### ISSUE THREAD

**Issue by ZiCog** [pegjs/pegjs#319]
I have problem regarding match actions not being run despite the fact that the matches must be made. Everything is parsed as expected. 

This is quite likely a bug in my understanding of how this should work but after many hours I don't see it.  

The following grammar produces a parser that matches the simple sequences, "A" or "AB" or "C" and rejects all else.   The action routine should return an object but but for the "A" and "AB" cases an array is returned.  

    start
      = input
    
    input
      = a:one b:two?
      / c:three
      {
        console.log("Rule: input");
        if (typeof a === "undefined") {a = null;}
        if (typeof b === "undefined") {b = null;}
        if (typeof c === "undefined") {c = null;}
        return {a:a, b:b, c:c}
      }
    
    one
      = "A"
    
    two
      = "B"
    
    three
      = "C"

Results:
"A" produces [ 'A', null ]
"AB" produces [ 'A', 'B' ]
"C" produces { a: null, b: null, c: 'C' }

This is NOT a peg online issue.

**Comment by Mingun** [comment]
This is because action assotiated only with `three` alternative, not all `input` rule. I'd like, you need transform it to form:
```js
input
  = a:one b:two? { return {a: a, b: b, c: null}; }
  / c:three { return {a: null, b: null, c: c}; }
  ;
one = "A";
two = "B";
three = "C";
```

**Comment by ZiCog** [comment]
Gosh, thank you.

Slaps head, hides in shame. So obvious when you say it. I just needed to look at the docs correctly...

Sorry for wasting you time.
