### ISSUE TITLE
/ not working as expected?

### ISSUE THREAD

**Issue by Kengur8** [pegjs/pegjs#326]
```javascript
start = val
ln = [\n\r]
float = digits:$[-0-9\.]+ { return parseFloat(digits, 10) }
str = str:$(!ln !"\"" .)+
val = float / str
```
parsing expression
> -a

results in error? I would expect it would parse str for me?

**Comment by dundalek** [comment]
By your definition the `-` is a valid float value, so it matches and end of input should follow. Try to define it something like this instead:
```float = digits:$('-'? [0-9]+ ('.' [0-9]+)?) { return parseFloat(digits, 10) }```

**Comment by Kengur8** [comment]
Ah, thanks. I though it was "all" or "nothing" matching. Although I would write it
> float = digits:$([-0-9.]+ !str) { return parseFloat(digits, 10) }
in my final version, I would have to practically "chain" all my "primitives" definitions that way...
