### ISSUE TITLE
Add ability to track node position

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#33]
PEG.js-generated parsers currently don't track position (line and column). I'd like to add this feature since it would be quite useful.

One way is to add `line` and `column` properties to each object returned as a match result:

```
start = "a" b:"b" { return [b.line, b.column]; } // Returns [1, 2] on the input "ab".
```

Another way is just to make special `line` and `column` variables available inside actions/predicates, referring to the position of the beginning of the current rule:

```
start = "a" "b" { return [line, column]; } // Returns [1, 1] on the input "ab".
```

The first way is more flexible, but this flexibility might not be needed actually. I am not sure which way I'll implement yet.

Both ways would hurt performance. To prevent this in cases where position tracking is not required, the tracking should be enabled only if `trackPosition` option with a truthy value is passed to `PEG.buildParser` when generating the parser.

**Comment by tomitrescak** [comment]
I know this is long closed, but how can I make this work? Am quite noob in this. I compiled my grammar with the "trackLineAndColumn': true" flag, but nodes still do not contain lines and columns. What else is needed?

**Comment by Turbo87** [comment]
@tomitrescak this feature has apparently changed a few times in the past. Have a look at the changelog for more information. tl;dr is that you need to use the `location()` function in your grammar
