### ISSUE TITLE
Rules won't match full regexps

### ISSUE THREAD

**Issue by darthtrevino** [pegjs/pegjs#330]
I'm writing a DSL to traverse HATEOAS links, and I'm running into an issue where a rule I've written won't match the full regexp. What I'm looking for is it to match hyphenated rel names like:

`view-profile`
`edit-thing`

However, I the parser won't match hyphens. So the match result is:

`view`
`edit`

The rule I have in place is:
```
identifier
  = chars:[_a-zA-Z]+[\-_a-zA-Z0-9]* { return chars.join(""); }
```

I've tried various online regexp testers, and they all match what I'm looking for. However, PEGjs will only match characters prior to the first hyphen. I've also tried this wit the PEGjs online version, and get the same result.

**Comment by Mingun** [comment]
This is because `chars` relate only for first symbol, one of `[_z-aA-Z]`. Rewrite you grammar as:
```
identifier
  = $([_a-zA-Z]+ [\-_a-zA-Z0-9]*)
```

**Comment by darthtrevino** [comment]
I see, thanks for the clarification!
