### ISSUE TITLE
Lazy position tracking can easily result in quadratic time behavior

### ISSUE THREAD

**Issue by swolchok** [pegjs/pegjs#337]
advance() re-scans the entire input if the current position is less than the last position line() or column() was used to get information about.

If PEG.js is used to build an AST and each node has position info, then most position queries will cause advance() to re-scan the input, because the AST will get built in postorder (bottom up).

Example: https://gist.github.com/swolchok/55e63535690ca7d62402

On my machine, with iojs 1.8.1, this prints:
5: 2 (ratio: 2)
6: 0 (ratio: 0)
7: 2 (ratio: Infinity)
8: 4 (ratio: 2)
9: 17 (ratio: 4.25)
10: 71 (ratio: 4.176470588235294)
11: 245 (ratio: 3.4507042253521125)
12: 781 (ratio: 3.1877551020408164)

Each step doubles the length of the input. If we were scaling linearly with the input, we would expect the ratio to be 2, but it's closer to 4, suggesting quadratic time behavior.

**Comment by kwesibrunee** [comment]
if you change the line() and column() functions and add a starter rule to the begining of the parser like so: https://gist.github.com/kwesibrunee/574ffb36c3bddfdd5376  you get a much more linear scaling. 

this approach uses much more memory though as it stores the line and column info for each char in the input. Perhaps a combining of the two approaches could get the desired result with less memory consumption.

**Comment by dmajda** [comment]
@swolchok Thanks for the report, we were hit by by this at [Jut](http://www.jut.io/) too. The original code was clearly sub-optimal so I rewrote it — see the commit message for details. If my solution doesn’t work for you, feel free to file another issue (ideally with suggestions on how to further improve it).
