### ISSUE TITLE
Allow case insensitive matching of literals

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#34]
Right now, matching literals case-insensitively is hard and ugly. For example, the only way to match "select" case-insensitively is:

```
select = [Ss][Ee][Ll][Ee][Cc][Tt]
```

Having one global flag for case-insensitivity would create problems when parts of a language is case-sensitive and another case-insensitive. Also combining languages (a feature I am thinging about for later) would be harder. Better way would be to signify case insensitivity for each literal separately, e.g. like this:

```
select = "select"i
```

**Comment by JanSemorad** [comment]
DOWNLOAD 
  = "DOWNLOAD"
  /   D O W N L O A D  {return "DOWNLOAD" }

D = [Dd]
O = [Oo]
W = [Ww]
N = [Nn]
L = [Ll]
A = [Aa]

**Comment by jtenner** [comment]
None of this change is documented. I've been using peg.js for years now and I had no idea this feature exists.

**Comment by futagoza** [comment]
@JanSemorad Is there a point to that post?

@jtenner Thank for pointing this out. I've been using PEG.js for 4 years now, and for some reason I always knew the feature was there but somehow never realised it wasn't documented 😆 Opened a new issue for this, see #518
