### ISSUE TITLE
Return a defined constant rule

### ISSUE THREAD

**Issue by anujku** [pegjs/pegjs#340]
<pre>
start = expression

spaceRuleDef = " "

someExpression = "SOME RANDOM TEXT" { return spaceRuleDef;}

</pre>

I want to do something like this? Is it possible ? I have one of the rules defined which returns a constant. If there is some rule that evaluates, I want to return this rule defined with constant. How can I achieve this? 

One way is creating a javascript constant. 

<pre>
{
  var SPACE_CONSTANT = "";
} 

start = expression

spaceRuleDef = " "

someExpression = "SOME RANDOM TEXT" { return SPACE_CONSTANT ;}

</pre>

But this means I am maintaining two copies of my constant which is not ideal. So is there a way to achieve this ?

**Comment by dmajda** [comment]
Issues are intended for bug reports and feature requests, please ask questions at the [Google Group](https://groups.google.com/forum/#!forum/pegjs). Thanks!
