### ISSUE TITLE
Question - how to return the AST tree

### ISSUE THREAD

**Issue by kaizer200** [pegjs/pegjs#344]
Hi,
1) I'd like to use the json grammar example, but would like to return the AST tree that the parser produced (by parsing my input json source). how should it be done?
2) does the parsed tree contains information about the nodes location (line number, column...)?

**Comment by atavakoli** [comment]
1. The example doesn't produce an AST; it produces the JS object that the JSON input represents. ASTs are mainly for describing languages/expressions, not data/data-structures like JSON.

2. Version 0.8.0 expose `line()` and `column()` functions in your actions, which give you the start of the expression's position. The current master has the `location()` function, which exposes start/end positions of the expression (see the README for details), but a tagged version has not yet been released with this feature (so if you're using bower, for example, which only has 0.8.0 registered, you will not have access to this function).

**Comment by atavakoli** [comment]
For these types of questions, I think you'll have better luck getting answers at the [Google Group](https://groups.google.com/forum/#!forum/pegjs) forum, instead of opening an issue.

**Comment by dmajda** [comment]
> For these types of questions, I think you'll have better luck getting answers at the [Google Group](https://groups.google.com/forum/#!forum/pegjs) forum, instead of opening an issue.

Yes. Issues are for reporting bugs and proposing enhacements.
