### ISSUE TITLE
How to use pegJS in an AngularJS application

### ISSUE THREAD

**Issue by adoueb** [pegjs/pegjs#346]
I have an AngularJS web application.

I'd like to use peg.js in my application. I've just written a peg.js grammar: CriteriaValue.pegjs and generated the parser with the command line: pegjs CriteriaValue.pegjs, which generated CriteriaValue.js.

Could someone explain to me how to use the parser ?

var result = parser.parse('my string'); doesn't work.

**Comment by lukas-vlcek** [comment]
Hi,

not an AngularJS user but I think you might get some hits from this
https://github.com/dvberkel/grunt-peg#wrap-in-an-angular-factory

Regards,
Lukas

**Comment by dmajda** [comment]
Issues are intended for bug reports and feature requests, please ask questions at the [Google Group](https://groups.google.com/forum/#!forum/pegjs). Thanks!
