### ISSUE TITLE
util.puts: Use console.log instead

### ISSUE THREAD

**Issue by yanickrochon** [pegjs/pegjs#356]
The source should be updated as in Node.js 0.12 (now stable), all calls to `util.puts` should be refactored to `console.log`.

**Comment by dmajda** [comment]
Thanks for the report, I [updated](https://github.com/pegjs/pegjs/commit/de1704f007523da4e8309d799adc24e9adcb0ea7) the `util.puts` and `util.error` calls now. Closing.

**Comment by yanickrochon** [comment]
Thank you!
