### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by caridy** [pegjs/pegjs#357]
any plans to update the npm pkg? hasn't been updated in 2 years :)

**Comment by Martii** [comment]
+1 ... would be nice.

**Comment by michel-kraemer** [comment]
The npm package is version 0.8.0. That's the latest official release of peg.js. I suppose the question would be more like "When will a new peg.js version be released?" :-)

**Comment by rse** [comment]
+1 for releasing the current state of peg.js under a new version number as soon as possible. Since 0.8.0 there were many many improvements which are worth to be available via a direct NPM dependency (instead of having to use local peg.js snapshots).

**Comment by tonypujals** [comment]
I was just about to file an issue. The published version on npm does not match the latest repo version despite having the same version number. For example, an `npm install` does not retrieve the latest version with trace option support (see [this line](https://github.com/pegjs/pegjs/blob/master/lib/compiler/passes/generate-javascript.js#L47) for example).

**Comment by vvakame** [comment]
:+1:

**Comment by vvakame** [comment]
in my project.
master/HEAD is over x9 faster than latest npm released version!

```
// RESULT peg.js 0.8.0
// parse0 x 2.78 ops/sec ±4.92% (11 runs sampled)
// parse1 x 123 ops/sec ±0.78% (79 runs sampled)
// parse2 x 119 ops/sec ±0.73% (79 runs sampled)
// Fastest is parse1

// RESULT peg.js master/HEAD
// parse0 x 26.06 ops/sec ±5.00% (49 runs sampled)
// parse1 x 123 ops/sec ±1.32% (81 runs sampled)
// parse2 x 121 ops/sec ±1.08% (80 runs sampled)
// Fastest is parse1
```

**Comment by muojp** [comment]
+1

**Comment by dmajda** [comment]
I will release 0.9.0 soon, I just filed an [issue](https://github.com/pegjs/pegjs/issues/364) listing remaining tasks. For more context, see [this thread](https://groups.google.com/d/topic/pegjs/yxQwweXxWmc/discussion) in PEG.js Google Group.

>  The published version on npm does not match the latest repo version despite having the same version number.

@tonypujals Obviously, code in master won’t match any released version except at the point of release. Keeping the old version number in `package.json` is less confusing than changing it to a version number of some non-existent future release. Ideally, I’d like to put something like `"version": "development"` there, but this would break  npm.

**Comment by tonypujals** [comment]
@dmajda ugh, that was a silly comment on my part. Can't even remember what was going through my mind at that point. I had just gotten trace support working, which I needed to pull from the repo since that wasn't published and somehow my brain went off on some weird tangent. Sorry about that ... and nice work, btw. :+1:
