### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#362]
PEG.js should support AMD. While I was reluctant to adding this in the past, AMD is still used in the wild and it certainly will be used for some time (most likely until ES6 modules get widespread browser support). This means supporting AMD will benefit PEG.js users. The best way implement this is via [UMD](https://github.com/umdjs/umd).

This issue captures two separate but related tasks:

  1. Making PEG.js itself UMD module.
  2. Making generated parsers UMD modules.

Note there must be a way to specify dependencies for generated parsers. A  `dependencies` option to `PEG.buildParser` would do the trick. It would take an object mapping dependency paths to names of variables used in the code, or just an array listing the dependency names (in case the dependency paths are the same as variable names). In the CLI, the same thing could be accomplished using a `--dependencies` option taking a comma-separated list of dependencies, each of which would be either a name or a path/variable name pair (separated by `:`).

Reference: #64

## Checklist

  - [x] Make PEG.js itself UMD module
  - [x] Move module system handling from `bin/pegjs` to `buildParser`
  - [x] Make generated parsers UMD modules
  - [x] Implement a way to specify parser dependencies in a module system independent fashion

**Comment by seeden** [comment]
Maybe the better idea is to use ES6 syntax for your project. And then automatically create commonjs/amd/umd library. For this purpose I can recommend you Babel and Webpack. Babel will create automatically ES5 version from your ES6. And webpack will create bundled library.

**Comment by dmajda** [comment]
ES6 & Babel: I’ll probably have a look at some point, but right now I don’t see that many benefits for PEG.js to warrant complicating the infrastructure and losing control over the exact shape of the code.

webpack: AFAICT, this is something more useful for websites rather than libraries. Also, I’ll touch it only if there is no other choice (it looks like a tangle of bad design from a superficial look).

**Comment by dmajda** [comment]
This is implemented now. Compared to the ideas outlined in the description, there were two changes:

  * The `dependencies` option of `PEG.buildParser` can’t take an array, just an object. This makes things a bit simpler.

  * The `--dependencies` CLI option which was supposed to describe the whole dependency list was replaced by a `-d`/`--dependency` option which describes an individual dependency (it can be specified multiple times). The advantages of this approach are:

    * It avoids handling of comma-separated lists (which could get messy quickly with more complex module IDs).
    * It is similar to already existing `--plugin` option.
    * It is similar to specifying dependencies in other environments (e.g. `--require` in Node.js).
