### ISSUE TITLE
In Node.js, resolve require paths relative to the grammar

### ISSUE THREAD

**Issue by jamestalmage** [pegjs/pegjs#363]
Grammar:
```js
{
  var helperModule = require('./helper-module');
}

StartRule = 
   // ...
```

Build:
```js
  var parser = PEG.buildParser(grammarSource, {output: 'parser'});
```

It will work if you do `{output: 'source'}` and write the output to a file in the same directory as the grammar (so that the relative path stays consistent).

Obviously this is due to the grammar source being `eval`ed in a completely different directory.

Ideally, those paths would resolve relative to the location of the grammar file.

**Comment by dmajda** [comment]
What would your ideal solution look like?

**Comment by jamestalmage** [comment]
I am not sure what the best way to do it is. For `{output: 'source'}`, I think it makes sense just to leave it as is.

Perhaps the best solution is to tell people not to use `{output: 'parser'}`, and just do an `eval` on their own in the correct directory.

```js
// runtime-generated-parser.js
var PEG = require('pegjs');
var grammarSource = require('fs').readFileSync('./grammar.pegjs', 'utf8');

module.exports = eval(PEG.buildParser(grammarSource, {output: 'source'}));
```

I think in that case eval would get a reference to `require` that included everything it needed.

**Comment by dmajda** [comment]
@jamestalmage Any `require` statements in the initializer are executed only when you call the `parse` method on the parser, not during `PEG.buildParser`. This suggests a solution where you pass a base directory to `parse`:

```javascript
var parser = PEG.buildParser(...);
parser.parse(..., { baseDir: ... })
```

The value of `baseDir` could be built any way you wish, including being derived from the location of used grammar file.

In the parser you can then do something like:

```
{
  var m = require(options.baseDir + "/m");
}
```

This looks like a good solution to me.

**Comment by gunar** [comment]
I endorse the solution that @dmajda proposed.

Should someone find themself thinking pegjs ought to be the one to fix `require`s with relative paths, hear me out:

#### 1. You would have to replace all calls to `require` in the Initializer block.

However, the current implementation doesn't parse the initializer. [It just copy-pastes the whole string](https://github.com/pegjs/pegjs/blob/b2a9dabcff19e339f32cb0dbfcffe7de15c7bcc9/lib/compiler/passes/generate-js.js#L1173).

Thus, how would we match and replace all `require()`s? A regex would suck. I've tried it. It looks bad, unsafe and bug-prone.

The other solution I see is parsing the code (`JavaScript -> AST`), mutating the AST, and then regenerating the code (`AST -> JavaScript`, e.g. [escodegen](https://github.com/estools/escodegen)). That would add too much weight to pegjs. Note that pegjs has currently no dependencies whatsoever, and that's pretty darn cool.

#### 2. Pegjs is (as far as I know) runtime agnostic.

And I think that's a good thing.

**Comment by jrunning** [comment]
@dmajda This is a great solution, but it took me 1) a whole lot of searching to find, and 2) a bit of trial-and-error to make it work. It would be great if this was documented explicitly in the README. Would you be interested in a PR for this?

**Comment by Qix-** [comment]
Another solution could be employed that is two-fold:

1. Add a `.filename` property to the `.generate()` function's options parameter that is the filename, if any, that was read in as the source.
2. Wrap the initializer block in a function that abuses shadowing.

For example, if my initializer block looks like this:

```javascript
{
    const someFunction = require('./some-utility');
}
```

the emitted initializer thus becomes the following (entirely untested):

```javascript
const path = require('path');

const baseDir = path.dirname(options.filename);

const _stubbedRequire = name => (name.length >= 2 && name.substring(0, 2) == './')
    ? require(path.join(baseDir, name))
    : require(name);

const initializer = (require => {
    /* INITIALIZER */
    const someFunction = require('./some-utility');
    /* END INITIALIZER */
})(_stubbedRequire);
```

This works with top-level packages, relative packages (to the grammar file itself, since `.filename` is supplied), as well as nested inclusions.

And it's not a hack. (:
