### ISSUE TITLE
Release PEG.js 0.9.0

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#364]
The 0.9.0 release is near! Here are the remaining steps:

 * [x] Fix #359
 * [x] Renumber bytecode instructions sequentially
 * [x] Upgrade all libraries used to their newest versions
 * [x] Test in all supprted browsers
 * [x] Update CHENGELOG.md
    * Use the [Keep a CHANGELOG](http://keepachangelog.com/) format?
 * [x] Update version to 0.9.0
 * [x] Release!

**Comment by michel-kraemer** [comment]
Awesome. Please let me know when the release is ready so I can also update the bower package.

**Comment by dmajda** [comment]
@michel-kraemer Sure, I’ll coordinate the release with you.

**Comment by dmajda** [comment]
PEG.js 0.9.0 is [released](https://groups.google.com/d/topic/pegjs/T2BraV9FPg4/discussion), closing.
