### ISSUE TITLE
npm version: 2 years old?

### ISSUE THREAD

**Issue by gilesbowkett** [pegjs/pegjs#366]
Hi, I worried from reading https://www.npmjs.com/package/pegjs that `pegjs` wasn't maintained any more. but I took a look at the commit history and development's still going strong.

**Comment by dmajda** [comment]
In the past, PEG.js development intensity varied greatly, depending mostly on the amount of time I could (and wanted) to spend on it. Things should be more stable now as PEG.js is basically my “20% project” at [Jut](http://www.jut.io/).

The 0.9.0 release is close, see [this comment](https://github.com/pegjs/pegjs/issues/357#issuecomment-131148150) and #364 for details.

**Comment by gilesbowkett** [comment]
cool, thanks!
