### ISSUE TITLE
[ASK] About the very first (early) parser for PEGjs grammar

### ISSUE THREAD

**Issue by aaron-elkins** [pegjs/pegjs#367]
Hi, it's very interested that PEG.js compiler uses `lib/parser.js` as a PEG.js grammar parser, and `lib/parser.js` again is generated by PEG.js compiler itself, much like a infinite loop.

And my problem is that what's your first version of lib/parser.js before PEG.js compiler was done?

Sorry for the bad expressive english, hopefully you understand them.

**Comment by dmajda** [comment]
This can be easily seen in Git history. Initially I just [included parser’s AST directly in PEG.js code](https://github.com/pegjs/pegjs/blob/c3dd696a3e915bb0399e7e53a8ffa7fd1715f634/lib/compiler.js#L506-L1323). A couple of days later I [converted it into a real grammar](https://github.com/pegjs/pegjs/commit/a43d1b33e35654c6f10f41ee81c095ecd781cea9).
