### ISSUE TITLE
Actions, Initializers, and Predicates in new versions of ECMAScript

### ISSUE THREAD

**Issue by blakelapierre** [pegjs/pegjs#369]
It would be nice to use some of the new ECMAScript features in grammars. Specifically, features like fat-arrow syntax, object/array destructuring, and shorthand object initialization.

Anyone know of any work on this?

**Comment by dmajda** [comment]
If you mean using new ECMAScript features in action/predicate/initializer code, this is already possible. PEG.js doesn’t touch user code and simply embeds it in the generated parser. To use the new features, you just need to run your parser in suitable JavaScript implementation or process it e.g. using Babel.

**Comment by blakelapierre** [comment]
Sorry, I was under the wrong impression that the user code was first parsed with the JS/ES 5.1 grammar.

Awesome project! Thanks!
