### ISSUE TITLE
Error message 'Can't find variable:' in version 0.9.0 - ok in 0.8.0

### ISSUE THREAD

**Issue by steinitz** [pegjs/pegjs#376]
Hi,

peg.js is great.  Thank you.

I’m testing some improvements to @mliebelt's chess pgn parser (https://github.com/mliebelt/PgnViewerJS) by using your excellent online generator.  The chess pgn parser below worked with version 0.8.0 but fails with version 0.9.0 with ‘Can't find variable: hm’ when given the valid input ‘1.e4’.  
What changes would I need to make to get it working with version 0.9.0?

Cheers,

Steve

---------------------------

{
    function makeInteger(o) {
        return parseInt(o.join(""), 10);
    }
}

pgn
  = pw:pgnStartWhite all:pgnBlack?
      { arr = (all ? all : []); arr.unshift(pw);return arr; }
  / pb:pgnStartBlack all:pgnWhite?
    { arr = (all ? all : []); arr.unshift(pb); return arr; }
  / whiteSpace?
    { return [[]]; }

pgnStartWhite
  = whiteSpace? pw:pgnWhite { return pw; }

pgnStartBlack
  = whiteSpace? cm:comment? whiteSpace? me:moveEllipse? all:pgnBlack
    { last = all[0]; last.moveNumber = me; last.commentMove = cm; return all; }

pgnWhite
  = whiteSpace? cm:comment? whiteSpace? mn:moveNumber whiteSpace? cb:comment? whiteSpace?
    hm:halfMove whiteSpace? nag:nags?  whiteSpace? ca:comment? whiteSpace? vari:variationWhite? all:pgnBlack?
    { arr = (all ? all : []); move = {}; move.turn = 'w'; move.moveNumber = mn;
      move.notation = hm; move.commentBefore = cb; move.commentAfter = ca; move.commentMove = cm;
      move.variations = (vari ? vari : []); move.nag = (nag ? nag : null); arr.unshift(move); return arr; }
  / endGame

pgnBlack
  = whiteSpace? cb:comment? whiteSpace?
    hm:halfMove whiteSpace? nag:nags? whiteSpace? ca:comment? whiteSpace? vari:variationBlack? all:pgnWhite?
    { arr = (all ? all : []); move = {}; move.turn = 'b'; move.notation = hm;
      move.commentBefore = cb; move.commentAfter = ca;
      move.variations = (vari ? vari : []); arr.unshift(move); move.nag = (nag ? nag : null); return arr; }
  / endGame

endGame
  = "1:0" { return ["1:0"]; }
  / "0:1" { return ["0:1"]; }
  / "1-0" { return ["1:0"]; } // SJS
  / "0-1" { return ["0:1"]; } // SJS
  / "1/2-1/2"  { return ["1/2-1/2"]; }
  / "*"  { return ["*"]; }

comment
  = cl cm:[^}]+ cr { return cm.join("").trim(); }

cl = '{'

cr = '}'

variationWhite
  = pl vari:pgnWhite pr whiteSpace? all:variationWhite? whiteSpace? me:moveEllipse? 
    { arr = (all ? all : []); arr.unshift(vari); return arr; }

variationBlack
  = pl vari:pgnStartBlack pr whiteSpace? all:variationBlack?
    { arr = (all ? all : []); arr.unshift(vari); return arr; }

pl = '('

pr = ')'

moveNumber
    = num:integer"."? { return num; }

integer "integer"
    = digits:[0-9]+ { return makeInteger(digits); }

whiteSpace
    = [ \t\r\n]+ { return '';} // SJS = " "+ { return '';}

halfMove
  = fig:figure? & checkdisc disc:discriminator str:strike?
    col:column row:row pr:promotion? ch:check?
    { hm = {}; hm.fig = (fig ? fig : null);
      hm.disc =  (disc ? disc : null);
      hm.strike = (str ? str : null);
      hm.col = col;
      hm.row = row;
      hm.check = (ch ? ch : null);
      hm.promotion = pr;
      hm.notation = (fig ? fig : "") + (disc ? disc : "") + (str ? str : "") + col + row + (pr ? pr : "") + (ch ? ch : "");
      return hm; }
  / fig:figure? str:strike? col:column row:row pr:promotion? ch:check?
    { hm = {};
      hm.fig = (fig ? fig : null);
      hm.strike = (str ? str : null);
      hm.col = col; hm.row = row;
      hm.check = (ch ? ch : null);
      hm.notation = (fig ? fig : "") + (str ? str : "") + col  + row + (pr ? pr : "") + (ch ? ch : "");
      hm.promotion = pr;
      return hm; }
  / 'O-O-O' { hm = {}; hm.notation = 'O-O-O'; return  hm; }
  / 'O-O' { hm = {}; hm.notation = 'O-O'; return  hm; }

check
  = '+'
  / '#'

promotion
  = '=' f:figure { return '=' + f; }

nags
  = nag:nag whiteSpace? nags:nags? { arr = (nags ? nags : []); arr.unshift(nag); return arr; }

nag
  = '$' num:integer { return '$' + num; }
  / '!!' { return '$3'; }
  / '??' { return '$4'; }
  / '!?' { return '$5'; }
  / '?!' { return '$6'; }
  / '!' { return '$1'; }
  / '?' { return '$2'; }
  / '=' { return '$10'; }
  / '∞' { return '$13'; }
  / 'D' { return '$220'; }

discriminator
  = column
  / row

checkdisc
  = discriminator strike? column row

moveEllipse
  = num:integer"."+ { return num; }

figure
  = [RNBQK]

column
  = [a-h]

row
  = [1-8]

strike
  = 'x'

**Comment by Mingun** [comment]
I think, it because from version 0.9.0 the parSer is generated in `strict` mode, and actions of this grammar don't conform to the rules of `scrict` mode, in particular, use undeclared variables (there is no `var` keyword before declaration of variables).

**Comment by steinitz** [comment]
Thank you @Mingun for your helpful reply.  That's a great clue.  I'll experiment with some judicious 'var's and see what happens.  

Being a newbie with peg, if you have any examples using a var directive, I'd be grateful to see it.

All the best

**Comment by steinitz** [comment]
Just a quick follow up.  I was able to solve my problem using your helpful suggestion.  I only had to add a 'var' whenever the code created a variable inside {} like so,

changed:
```
{ hm = {}; 
  hm.fig = (fig ? fig : null);
  hm.disc = (disc ? disc : null);
  hm.strike = (str ? str : null);
  hm.col = col;
  hm.row = row;
  hm.check = (ch ? ch : null);
  hm.promotion = pr;
  hm.notation = (fig ? fig : "") + (disc ? disc : "") + (str ? str : "") + col + row + (pr ? pr : "") + (ch ? ch : "");
  return hm; }
```
to:
```
{ var hm = {}; 
  hm.fig = (fig ? fig : null);
  hm.disc = (disc ? disc : null);
  hm.strike = (str ? str : null);
  hm.col = col;
  hm.row = row;
  hm.check = (ch ? ch : null);
  hm.promotion = pr;
  hm.notation = (fig ? fig : "") + (disc ? disc : "") + (str ? str : "") + col + row + (pr ? pr : "") + (ch ? ch : "");
  return hm; }
```
Now all is well.  Thanks again.

**Comment by dmajda** [comment]
@steinitz Great that you were able to solve your problem. Next time, please take questions like this to the [PEG.js Google Group](https://groups.google.com/forum/#!forum/pegjs). Issues are meant only for reporting bugs and requesting enhancements, anything else creates clutter. Thanks.

**Comment by steinitz** [comment]
@dmajda I understand.  Thanks for making your feelings clear.  I confess that I do occasionally use github's issue feature for marginal issues due to its lack of a comment feature.  

In this case the implicit bug was '0.9.0 breaks my code'.  The 'bug' had caused me several hours of difficulty.  However, I preferred to frame my post as a cooperation, a discussion, rather than as a blatant bug report.  If I had known your feelings, of course I would have thought twice about presenting my 'bug' as a discussion.

Thanks again for your fine work on peg.

All the best
