### ISSUE TITLE
Crash with cleanupExpected function splicing through a very large "expected" array

### ISSUE THREAD

**Issue by Hugheth** [pegjs/pegjs#377]
Hi there,

Currently working with a Java 1.7 grammar.

When I try and parse ``` ( ( ) ) ``` PEG.js crashes out. It first detects an exception and calls throw peg$buildException( null, peg$maxFailExpected, peg$maxFailPos );

However the peg$maxFailExpected has 260416 elements, causing the cleanupExpected function which removes duplicates for the match message to loop practically indefinitely on splice operations.

How could the maxFailExpected array get so long? Is there something wrong with the grammar? Presumably even so there shouldn't be so many duplicates in the expected array?

https://github.com/mazko/jsjavaparser/blob/master/src/Java.1.7.pegjs

**Comment by dmajda** [comment]
@Hugheth Your report is incorrect — parsing `( ( ) )` alone works fine. I saw you filed https://github.com/mazko/jsjavaparser/issues/2 where you included full hang-inducing input. Copying it here for the record:

```java
package js.java.parser;

import static java.lang.System.out;

import java.util.*;

public class HelloWorld {
  public static void main(final String[] args) {

        ( ( ) )

  }
}
```

I didn’t inspect the Java grammar in detail but to prevent so many duplicate expectations you should probably generate your Java parser using the `--cache` CLI option or the `cache: true` API option. This will avoid matching low-level rules again and again at the same position, which generates the expectations.

Now, handling many expectations in the parser was indeed suboptimal and I [improved it](https://github.com/pegjs/pegjs/commit/d34faba59e8940d62c2ee3a55e45edf9d9c2b441). This change makes a parser generated from the Java grammar work on your input even with caching disabled.

With this, I consider the problem fixed. Thanks for reporting it!
