### ISSUE TITLE
Syntax 'inheritance'?

### ISSUE THREAD

**Issue by algebraic-brain** [pegjs/pegjs#378]
Hi!

Now I'm planning development of equational proof assistant for using directly in browser. It would be convenient to use PEG.js for in-browser EPA, but I need extensible grammars. Something like inheritance - one grammar inherit rules from another, checking that rule names are different. Is it possible somehow in the current PEG.js version? Any hack?

**Comment by Artazor** [comment]
You can take a look at the SDF modular syntax definitions (with generic non-terminals etc) from the ASF+SDF meta-system (it is not PEG-based, it is GLR-based Tomita automata based parser/graph rewriter). I would be happy to see PEG syntax modules as powerful as SDF modules.

**Comment by algebraic-brain** [comment]
Thanks a lot, very interesting! Of couse it is the right tool (I see it by keyword 'many-sorted algebras'). But difficult for my plan of implementation, PEG.js-in-browser is much easier. I'd hack PEG.js instead of  using ASF+SDF that compiles to C program.

**Comment by Mingun** [comment]
You need import feature. Implementing it require some work -- you can look at my branch https://github.com/Mingun/pegjs/tree/include-pass and for my PR fo this -- #308 for example.

**Comment by algebraic-brain** [comment]
Mingun, thanks for links you provided.

Anyway I realized that I will need some other improvements, so maybe it's better for me to use PEG.js as backend.
