### ISSUE TITLE
Import/include other grammars

### ISSUE THREAD

**Issue by ceymard** [pegjs/pegjs#38]
It could be extremely useful to have the ability to define grammars by importing rules from other grammars.

Several ideas ;

```
@include "expression.pegjs"
(or @from "expression.pegjs" import expression)

tag_if
    = "if" space? expression space? { ... }

@import "expression.pegjs" as expr

tag_if
    = "if" space? expr.expression space?
```

Ideally, this would not re-generate the whole code in every .pegjs that includes another ; maybe we would have to modify a little the behaviour of parse() to something of the like ;

Editing as per what you were saying in the `options` issue ;

```
parse(input, startRule)
->
parse(input, { startRule: "...", startPos : 9000 })
```

And at the end, if `startPos != 0 && result !== null`, we don't check if we went until `input.length`, but instead return the result as well as the endPos (don't really know how to do that elegantly - maybe simply modifying the options parameter ?).

It would allow reusability of grammars and modularisation of the code, which I think are two extremely important aspects of coding in general.

**Comment by Mingun** [comment]
I implement this in #308 in generic way: inclusion of grammar is only one way to implement decomposition rules.

**Comment by lbeschastny** [comment]
:+1:

**Comment by AndreTheHunter** [comment]
:+1:

**Comment by rumkin** [comment]
Awesome! :+1:

**Comment by dmsnell** [comment]
@dmajda I'm coming late to this party, but I wonder how often we need to import many rules from another library. I would love to be able to import things like `Url` and `Email` into my composed grammars but I don't care that `Url` may also have things like `HierarchicalPart` and `AsciiLetter`. Do you think something like Node's named exports would be a viable way forward, keeping the benefits of namespacing but allowing direct named imports?

```pegjs
import { SchemalessUrl, Url } from "./Urls.pegjs"

Token
  = PhoneNumber
  / Url
  / SchemalessUrl
```

Namespacing has been an issue for me as I try and explore writing otherwise-composable grammars. I'm stuck right now including files in files and naming things the way PHP functions were named before they introduced proper namespaces: `UrlIpHost`, `HtmlQuotedString`, etc…

**Comment by eraxillan** [comment]
@dmajda @futagoza 

Any progress on this issue? or the primary discussion living now on #473 ?
My grammar file is growing very fast :(
It would be nice to split it several ones

**Comment by mikeaustin** [comment]
I wouldn't mind being able to split grammars between files, simply for organization and composition. It would make them easier to test and re-use, as well as providing a way swap grammars dynamically, maybe? Just some thoughts.

The JavaScript example that I used as a base is over 1,300 lines. It took a while to learn where everything was, and jump around and edit different sections.

**Comment by eraxillan** [comment]
@mikeaustin I see this feature as some kind of Node.JS `required`:
> cat bash.pegjs
{
const _ = require("whitespace");
const LB = require("line_break");
const CodeBlock = require("code_block");
const BoolExpr = require("boolean_expression");
}
...
IfStatement = "if" _ "[" BoolExpr "]" _ ";" _ "then" LB? CodeBlock "fi"

**Comment by jodevsa** [comment]
i agree, splitting grammars and making them modular is a great feature, however handling these case's would be  a a problem:
1- sub-grammar that relies on a global variable that was defined in the main grammar code ? 
2- duplicate variables and grammar name ? 

IMO, a temporally convenient approach  would be creating a new addon for pegjs that  defines a keyword for importing (for example load(anotherGrammarFileLocation) ),
build a reg-exp or a peg grammar to detect that keyword and substitute it with "anotherGrammarFile Location" content , and  send the substituted code to PEG.js 

until someone comes with a convenient idea that can be added as a built-in feature
