### ISSUE TITLE
parsing percent sign issue

### ISSUE THREAD

**Issue by ssteffl** [pegjs/pegjs#384]
i am trying to parse something like ".*" (matching the double quotes too)

Im using this in my grammar file right now:

String
 = str: ("\"" [^\"]+ "\"") { return str[1].join(""); }

which works for everything except "%foo%" for some reason (double quotes included)

but the following work: "%foo" or "fo%o" or "foo"

it just seems to be when i put the % right before the second " that causes a parser error

**Comment by ssteffl** [comment]
actually "%foo" doesn't work either. i found that it ends up converting it to "?o" (including double quotes)

It looks like when PEGjs parser comes across a % it does some funky stuff with the following couple characters.

**Comment by dmajda** [comment]
@ssteffl Can you please provide a description of your environment and exact steps to reproduce this?

**Comment by dmajda** [comment]
No reply, closing.
