### ISSUE TITLE
Example JS parser accepts incorrect syntax 

### ISSUE THREAD

**Issue by YemSalat** [pegjs/pegjs#389]
The JS parser accepts incorrect syntax, like: `1 = 2`

I have not looked much into it, but I think the problem stems from having a `MemberExpression` on the left hand side of `AssignmentExpression`

**Comment by dmajda** [comment]
This is not a bug. According to ECMA-262, 5.1 Edition, `AssignmentExpression` [has `LeftHandSideExpression` on its LHS](http://www.ecma-international.org/ecma-262/5.1/#sec-11.13), which can be [expanded to `PrimaryExpression`](http://www.ecma-international.org/ecma-262/5.1/#sec-11.2). And a numeric literal is a valid `PrimaryExpression`, meaning expressions like `1 = 2` are perfectly *syntactically* valid. The fact that they are not *semantically* valid is irrelevant to a parser.
