### ISSUE TITLE
Literal string containing curly brace not recognized within code block

### ISSUE THREAD

**Issue by balagge** [pegjs/pegjs#398]
Following pegjs sources do not compile:

`E = . {return '{'; }`

`E = . {return "{"; }`

`E = . {return '}'; }`

`E = . {return "}"; }`

Same applies for any string literal that contains opernig / closing curly braces  in any code block.
It seems that the string literal within the code block is not parsed correctly.

**Comment by dmajda** [comment]
See #89.
