### ISSUE TITLE
Q:Is it possible to require() from a package a suite of symbol/token classes and use these instead of returning plain javascript objects?

### ISSUE THREAD

**Issue by silkentrance** [pegjs/pegjs#401]
For example, consider a package that defines

```
class Symbol
{
 ...
}
```

would it be possible to define rules that would return instances of Symbol instead of just a plain javascript object during parse?

E.g. require the symbol class at the beginning of the parser definition?
Or would I require a factory function that will return the required symbol instance?

```
{
      var Symbol = require('symbol');
}

Symbol
   = char:.
   {
        return new Symbol(location(), char);
   }
```

**Comment by Tyler8oliver** [comment]
You can do either, it kind of depends on what you are trying to do. I require other classes in my parser to process the parsed data.

**Comment by silkentrance** [comment]
Thanks for the info!
