### ISSUE TITLE
Q:location() function is fine but am I able to associate this with a given input file name?

### ISSUE THREAD

**Issue by silkentrance** [pegjs/pegjs#402]
Is there a possible chance of passing the input file name to the parser so that one can associate a given parse location with that file name?

**Comment by Mingun** [comment]
Now it is impossible, but you can make PR which to add the `newLocation` hook-function to parser `options`, with this usage scenario:
```js
var fileName = ...;
var grammar = fs.readFileSync(fileName, 'utf8');
PEG.buildParser(grammar, {
  newLocation: function(loc) { loc.fileName = fileName; return loc; }
});
```
If you don't make PR, it will be made by me in the next week or two.

**Comment by silkentrance** [comment]
@Mingun Thank you very much!

**Comment by silkentrance** [comment]
@Mingun just found out that one can pass additional options to the parser, so one could pass the input file name as part of that object and have custom code extract that option and a factory function for augmenting the current location, e.g.

```
{
    function agumentLocation(location)
    {
          location.file = options.file;
          return location;
    }
}

And, given the generated parser, I think that this will be possible, too.

**Comment by silkentrance** [comment]
Closing as I found a working solution.

**Comment by dmajda** [comment]
@silkentrance The solution with `options` works but this looks like a common use case and I think it warrants a better solution. I filed #421 to track that.
