### ISSUE TITLE
output to php

### ISSUE THREAD

**Issue by seeden** [pegjs/pegjs#404]
Hi

Do you have any plan to add support for other languages? I mean output only. 
I would like to add php support. Do you have any tips what I need to do?

**Comment by avdg** [comment]
This would probably mean writing a separate code generator

**Comment by Mingun** [comment]
Such generator already written, see https://github.com/Nordth/php-pegjs

**Comment by YemSalat** [comment]
https://github.com/hafriedlander/php-peg ?

**Comment by dmajda** [comment]
@seeden PEG.js is JavaScript-only project and there are no plans to incorporate support for other languages. This is a deliberate design choice to constrain project scope. This of course didn’t stop people to add support for various languages via plugins, which is fine, it’s just not *really* supported.

For PHP, you can use the project @Mingun pointed out, or you can write your own using the [plugin API](https://github.com/pegjs/pegjs/issues/106#issuecomment-12198352). You basically need to replace the [JavaScript generator](https://github.com/pegjs/pegjs/blob/5eb6225ef0767d959e570f1bc66c04af8eb6aff5/lib/compiler/passes/generate-js.js) and maybe the [bytecode generator](https://github.com/pegjs/pegjs/blob/5eb6225ef0767d959e570f1bc66c04af8eb6aff5/lib/compiler/passes/generate-bytecode.js) with your own implementations.
