### ISSUE TITLE
Running pegjs cli empties a grammar file if it has no extension

### ISSUE THREAD

**Issue by AlexGustafsson** [pegjs/pegjs#405]
### What

Running `pegjs example` where `example`is a file containing grammar will result in the file being emptied and the following message being written to the command prompt:

```
1:1: Expected code block, comment, end of line, identifier or whitespace but end of input found.
```

### Replicate

* Create a file without an extension, for example `example`. 
* Add the content from the [json parser example](https://github.com/pegjs/pegjs/blob/master/examples/json.pegjs).
* Run `pegjs example`
* Watch how the file is now empty.

### Configuration
* MacBook Pro running OS X El Capitan 10.11.2 (15C50)
* Node v5.4.0
* PegJS v0.9.0

**Comment by silkentrance** [comment]
bugger, confirmed.

**Comment by dmajda** [comment]
@AlexGustafsson This is indeed a bug. Thanks for the report and sorry for any trouble it caused you. Fix is coming in a minute.
