### ISSUE TITLE
Use ESLint to enforce code style

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#407]
After [switching from JSHint to ESLint](https://github.com/pegjs/pegjs/issues/406), use it to enforce coding conventions. More specifically, go through [ESLint’s rules](http://eslint.org/docs/rules/), enable all that make sense, and configure them to match how PEG.js code is written.

**Comment by silkentrance** [comment]
Have a look at https://github.com/coldrye-es/eslint-config-coldrye for a starter. These rules are rather restrictive, so you might want to loosen them up a bit.

**Comment by dmajda** [comment]
@silkentrance Thanks but I’ll go build the rule configuration myself.

**Comment by dmajda** [comment]
This is done now. I ended up writing a detailed ESLint configuration and releasing it as a [separate project](https://github.com/dmajda/eslint-config-dmajda). This way it won’t be tied to PEG.js and I (or anyone else) will be able to use it in other projects.

**Comment by pjmolina** [comment]
Very clean and elegant way to have ESLint settings apart.
