### ISSUE TITLE
Parse errors should build up a stack trace

### ISSUE THREAD

**Issue by silkentrance** [pegjs/pegjs#411]
This would be a follow up to #262.

Given the top level symbols in the grammar shown in #410, I would like the parser to be able to report that for example the ``Translation`` symbol could not be found instead of reporting something like ``Expected ws or nl but found eof``.

While at the same time it should be possible to have the parser report syntax errors on sub level symbols such as TranslationId and so on.

The reasoning here being that parse errors found at the sub level should bubble up, given you a stack trace of failed symbol matches rather than just that of the top level symbol.

E.g. given the following input and the grammar from #410 

```
#= lang en-US
#!
```

this should report that a ``translation`` was missing, provided that the top level symbol ``Translation`` had been labelled, and that it was caused by the translation id being malformed, e..g

```
SyntaxError: translation missing
caused by
SyntaxError: malformed translation id
```

Whereas

```
#= lang en-US
```

should report that a ``translation`` is missing and not that either '#' or '!' or whatever basic literal was expected.

What about that for a valid use case?

**Comment by silkentrance** [comment]
For example ``peg$failStack = []`` could be used as a stack for recording silent fails during parse, e.g.

{{{
if (sx === peg$FAILED && peg$silentFails > 0)
{
    peg$failStack.push(peg$buildException(..., {trace : false}));
}
}}}

and then when it comes to building the final exception

{{{
if (result == peg$FAILED)
   throw new peg$buildException(..., {trace:true})
}}}


While SyntaxError would then report the stack trace information upon getting the trace property. This however, needs some adjustments to be made to the SyntaxError class, see for example [esbases](https://github.com/coldrye-es/esbases) for a working solution that allows you to subclass Error including augmenting the stack property's value.

**Comment by silkentrance** [comment]
Yet, after having patched the sources so I can get at least part of the above described behavior, I realize that is very difficult to decide whether a none-or-multiple, or one, or one-or-multiple rule is mandatory and should lead to a parse error or whether it needs to be ignored unless one is able to provided additional hints to the parser in the grammar and in context of a specific symbol. And, given the given architecture, it is quite impossible to tell the context of a given symbol unless more information is passed to the individual rule match functions. But I might be mistaken here and there might be a context providing facility that would allow a given rule to figure out whether it is purely optional or whether it is actually required to add to a/o generate a trace of its parse errors.

**Comment by silkentrance** [comment]
Having settled upon just throwing the error and not generating a trace will just do the trick, needs a bit more testing though...

**Comment by silkentrance** [comment]
Directly related to #410

**Comment by silkentrance** [comment]
Best thing I can think of would be to provide additional hints in the grammar, say

```
Translation
    = NL*
      comments:~Comment*
      id:TranslationId
      context:VariationContext?
      variations:Variation+
    {
        return {
            type     : 'translation',
            location : location(),
            id: id,
            context: context,
            comments : comments,
            variations: variations
        };
    }
```

Where

```
TopLevelSymbol
      comments:~Comment*
```

would tell the parser generator that ``Comment*`` is definitely optional and will never be recorded as a parse error and, what is important here, only in the context of the ``TopLevelSymbol``.

Whereas the definition of the rule ``Comment`` as such

```
~Comment
     = ...
```

would make the parse ignore any parse errors regardless of any context.

**Comment by dmajda** [comment]
Sounds like you want #11 after all (your `~` hint is a means to implement that). I’m closing this as a duplicate.

Overall, I’m aware that error handling is not ideal in all cases, I want to look at that area again sometime after 1.0.0.

**Comment by silkentrance** [comment]
@dmajda Thanks,I did not relate that issue to the one I was seeing.
