### ISSUE TITLE
Can "peg$" be removed?

### ISSUE THREAD

**Issue by matthew-dean** [pegjs/pegjs#413]
Can you add an option to remove "peg$" prefixes (from functions, etc) from the generated parser? It just adds to the file size and makes the generated parser harder to read.

**Comment by dmajda** [comment]
The prefix is there for a reason, namely to prevent conflicts with user identifiers (see #92). Adding a possibility to remove it would open a window for bugs.

I agree with you that eliminating the prefix would improve readability of generated parsers. However I don’t buy the size argument — if this is a concern, the right thing is to use a minifier (it is not PEG.js’s job to care about size of identifiers in generated parsers).

Overall, I don’t think the (slight) readability improvement isn’t worth the cost of adding an option and opening said window.

**Comment by matthew-dean** [comment]
Oh, I thought I read in some other documentation (or issue) that JavaScript reserved words were disallowed anyway by the parser generator?

**Comment by dmajda** [comment]
This about clash of user identifiers with internal parser identifiers (which the `peg$` prefix prevents), not a clash with JavaScript reserved words.

**Comment by matthew-dean** [comment]
Ah.
