### ISSUE TITLE
Improve expectation definitions

### ISSUE THREAD

**Issue by matthew-dean** [pegjs/pegjs#414]
Comparing two single characters against each other is generally slower than comparing two numbers. (See: http://stackoverflow.com/questions/4904179/why-is-integer-comparsion-faster-then-string-comparion) So, a number of parsers handle this by converting characters to numbers and doing a character value comparison.

In other words, it might be slightly faster if PEG instead of generating this:
```
        peg$c24 = ".",
        peg$c25 = { type: "literal", value: ".", description: "\".\"" },
        peg$c26 = "#",
        peg$c27 = { type: "literal", value: "#", description: "\"#\"" },
```
The parser might generate:
```
        peg$c24 = 46,
        peg$c25 = { type: "char", value: 46, description: "\".\"" },
        peg$c26 = 35,
        peg$c27 = { type: "char", value: 35, description: "\"#\"" },
```
(Also not sure why all the redundancy of listing the character 3 times.)

Unless someone who knows more about this in terms of parsing wants to chip in, that might help with parsing speed.

**Comment by matthew-dean** [comment]
Here's another performance optimization:

The PEG.js parser generator creates objects like:
```
peg$c39 = { type: "literal", value: ">", description: "\">\"" },
peg$c41 = { type: "literal", value: "+", description: "\"+\"" },
peg$c43 = { type: "literal", value: "~", description: "\"~\"" },
peg$c45 = { type: "literal", value: "|", description: "\"|\"" },
```
Even though these objects look the same, V8 and other JavaScript engines have no way to optimize them. The way the V8 engine works is to look at the shape of the function prototype and create hidden classes based on that shape. Objects that are instances of that prototype can then use those hidden classes, which only have to be created once.

The details of V8's hidden classes is here: https://developers.google.com/v8/design#prop_access

In the above example, the objects don't share the same prototype, so V8 unfortunately will create separate classes for all of them. However, this can be greatly improved by doing this:
```
function token(literal, value, description) {
  this.literal = literal;
  this.value = value;
  this.description = description;
}
peg$c39 = new token("literal", ">", "\">\"" ),
peg$c41 = new token("literal", "+", "\"+\"" ),
//etc...
```
In both examples, you're still just creating JS objects, but in the second case, V8 can re-use the hidden classes it generated from the shape of the token function. As long as you don't dynamically add properties to a created object, those classes can be re-used.

**Comment by dmajda** [comment]
> So, a number of parsers handle this by converting characters to numbers and doing a character value comparison.

PEG.js already [does this optimization](https://github.com/pegjs/pegjs/blob/e61c23c634a873f6e62f33d933d7761068214b24/lib/compiler/passes/generate-js.js#L634-L640). What might be confusing is that while the character code gets inlined, the const is still kept (it is used when pushing a match result on the stack). It might be cleaner to use a separate bytecode instruction with a numeric const instead (e.g. `MATCH_CHAR`), but I think I prefer bytecode simplicity and keeping the optimization at the code generator level.

> (Also not sure why all the redundancy of listing the character 3 times.)

The first const (e.g. `peg$c24` in your initial example) defines the actual value, the second const (e.g. `peg$c25`) defines an expectation which is used when reporting errors. It could probably be built differently (e.g. referring to the first const) or even lazily, but this would complicate parser code. This is probably worth some tweaking and experimenting.

> In the above example, the objects don't share the same prototype, so V8 unfortunately will create separate classes for all of them.

I wouldn’t be surprised if V8 optimized even this case these days — but I’m certainly not an expert here.

In any case, these objects are used only in reported errors and their properties are typically accessed only to build an error message. This is far from a performance bottleneck. On the other hand, defining the expectations the way you suggest may lead to shorter code. Again, probably worth some tweaking and experimenting.

---

I’ll keep this issue open as the definition of expectations is probably something that can be improved — if not form performance POV, then from code size & redundancy view. I’ll have a look at this in the 0.11.0 cycle (per [development roadmap](https://github.com/pegjs/pegjs/wiki/Roadmap)).

If you want to tackle some of this yourself sooner, you are welcome to. In that case, please run any changes through `tools/impact` to have an idea whether & how much they really improve things and include the results when submitting a PR. Thanks.

**Comment by matthew-dean** [comment]
@dmajda Thanks for your explanations! I actually wondered if it was in fact inlining the value by looking at the code, but wasn't quite sure. Makes sense.

I've looked at a few parser generators and PEG.js is pretty great. It has a great combination of simplicity in the grammar and ease of mapping grammar to JS. It's the online tool that's really helped me get a feel for it.

**Comment by Mingun** [comment]
> If you want to tackle some of this yourself sooner, you are welcome to. In that case, please run any changes through  tools/impact  to have an idea whether & how much they really improve things and include the results when submitting a PR. Thanks.

This optimization doesn't give visible improving of perfomance, on average 0±1% (`master` is e61c23c634a873f6e62f33d933d7761068214b24, [expected-as-class](https://github.com/Mingun/pegjs/tree/expected-as-class) is branch in my fork):
```sh
$ ./impact master expected-as-class
Measuring commit master... OK
Measuring commit expected-as-class... OK

Speed impact
------------
Before:     183.44 kB/s
After:      185.40 kB/s
Difference: 1.06%

Size impact
-----------
Before:     721705 b
After:      718995 b
Difference: -0.38%

(Measured by /tools/impact with Node.js v0.10.18 on MINGW32_NT-6.0 1.0.18(0.48/3/2) i686.)
```
But together with optimization #399 and #400 measurement stablly give >8% of an acceleration (unlike optimization separately where measurements are unstable and strongly float both towards reduction, and towards increase in perfomance, `master` is e61c23c634a873f6e62f33d933d7761068214b24, [optimization](https://github.com/Mingun/pegjs/tree/optimization) is branch in my fork):
```sh
$ ./impact master optimization
Measuring commit master... OK
Measuring commit optimization... OK

Speed impact
------------
Before:     186.00 kB/s
After:      201.27 kB/s
Difference: 8.20%

Size impact
-----------
Before:     721705 b
After:      523996 b
Difference: -27.40%

(Measured by /tools/impact with Node.js v0.10.18 on MINGW32_NT-6.0 1.0.18(0.48/3/2) i686.)
```

**Comment by matthew-dean** [comment]
@Mingun Oh neat. Well sounds like those suggestions are worthwhile then. That's pretty cool.

**Comment by dmajda** [comment]
I recently [changed how expectations are constructed](https://github.com/pegjs/pegjs/commit/5a4d04fa90471dd1ac1d7294c3083fcbdc732407). I think that change addresses concerns discussed in this issue (opportunity for performance optimization by the JavaScript engine, code length & redundancy) so I’m closing it.

If you feel further improvements would be beneficial, please open separate issues with specific suggestions.
