### ISSUE TITLE
Feature suggestion: shorthand syntax for "Element (Separator Element)*"

### ISSUE THREAD

**Issue by HyeonuPark** [pegjs/pegjs#425]
## Why?

With PEG.js, I wrote such syntax a lot. For example, if I want to parse JS array naively, it's PEG.js syntax form will be this

```
Array = "[" first:Expression rest:(comma Expression)* "]" {
  return [first].concat(rest.map(el => el[1]))
}
```

And it must not be my sole experience. Building a list of elements are unnecessarily complicated.

## What do you want?

So my suggestion is, making another operator to represent such statement, like this.

```
Array = "[" arr:(Expression &* comma) "]" {
  return arr
}
```

In this example, "&*" operator is binary operator. Because it takes two expression. I know PEG.js doesn't have binary operator yet, but why not in the future?

**Comment by dmajda** [comment]
I agree that expressing lists with separators is currently cumbersome, I plan to tackle this after 1.0.0. See #107 where various ideas are considered, including an operator approach similar to what you suggested.

Closing this issue as duplicate and thanks! (I take this issue as a vote.)
