### ISSUE TITLE
Changing an error message for unexpected character

### ISSUE THREAD

**Issue by kenginga** [pegjs/pegjs#426]
My idea is to change an error message which is displayed when an unexpected character is detected in the input.
This will help user to understand the meaning of the error.

The following example shows the current situation and my request.

<<< PEG.js grammer >>>
start = foo bar baz
foo = 'a'
bar = 'b'* / 'c'
baz = 'd'

<<< input >>>
acd

<<< Current error message >>>
Line 1, column 2: Expected "b" or "d" but "c" found.

<<< New error message >>>
Line 1, column 2: Expected "b" or "d" but "c" found after matching 'b'* at Line 3 of PEG.

An example above shows a typical error. The user expects an input 'acd' to match the PEG. However, it shows an error reporting unexpected character found. And, it may be hard to determine where the problem is.

New error message points out which part of PEG has been matched right before encountering to unexpected character. By the given information, the user can understand that it has been matched to 'a', but it has not been matched 'c' yet because the error occurred in Line 3 of PEG. So the user can focus on Line 3, not Line 2 nor 4.

If it is hard to show the line number of PEG, showing only the expression 'b'* will be still helpful. 

<<< New error message alternative >>>
Line 1, column 2: Expected "b" or "d" but "c" found after matching 'b'*

BTW, in the example above, the user may change Line 3 as below to avoid matching to 'b'*. Then the input will be parsed successfully.

bar = !'c' 'b'* / 'c'

**Comment by Mingun** [comment]
In this case the alternative `'c'` the rule `bar` generally will never be matched and this can be catched at parser generation stage. Such solution will be more useful and generalized and this is already tracked as #424. Warning message may looks like:
```
Line 3, column 13: Detected unreachable choice alternative 2, previous alternatives cover all variants
```

**Comment by dmajda** [comment]
@Mingun Sure, see the [originating discussion](https://groups.google.com/d/topic/pegjs/4dqWQQKZDng/discussion). I still find the idea interesting enough to warrant some investigation.

@kenginga After some thinking, the biggest problem I see in your proposal is the definition of “part of PEG [which] has been matched”. For example, what if the `bar` rule is something like:

```
bar = ('x'* / 'y'* / 'z'*) / 'c'
```

Do we show `('x'* / 'y'* / 'z'*)`? Or do we show just `'x'*`? And what if some of the inner choices are in separate rules? And what if the whole `'x'* / 'y'* / 'z'*` expression is? Also, do we separate expressions only on choices or also on other boundaries?

I think these questions (and maybe some more) need to be answered before this proposal is implementable, leading to some general rules governing the behavior.

I also need to see some more users weighing in saying this would be useful for them (it would be wrong to introduce a solution to a problem almost nobody has).

**Comment by kenginga** [comment]
In that case, just 'x'* should be shown.

**Comment by dmajda** [comment]
I thought about this a bit more. The original request is motivated by a need of grammar writers to understand why parsers generated from grammars they develop fail (in other words, a need for grammar debugging). However, syntax error messages are not intended for grammar writers but for parser *users*. They need to make sense even without the grammar and they should not depend on it too much. They are certainly not a good place for what is essentially debugging information.

The proposed solution is in conflict with this philosophy. I also think that grammar debugging is already adequately addressed by [tracing](https://github.com/pegjs/pegjs/commit/da57118a43a904f753d44d407994cf0b36358adc). Given that I’m closing this issue.
