### ISSUE TITLE
Support reporting multiple errors/warnings in PEG.js

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#431]
Right now, `peg.generate` can report only one error (which is always fatal) and can’t report any warnings. It would be useful to support reporting multiple errors and use the same mechanism for reporting warnings. This is needed for #327 and #430 and it would also allow making some errors non-fatal (which would allow e.g. to report all duplicate rules at once, not one-by-one like now).

**Comment by dmajda** [comment]
Technically, this change requires changing the current exception-based error reporting API to something else. I’m thinking about several options:

  1. **Report errors/warnings as part of `peg.generate` result.** For example, the result could become an object with `result`, `errors`, and `warnings` properties.

  2. **Report errors/warnings using additional properties/methods.** For example, there could be `peg.warnings` and `peg.errors` properties, filled by `peg.generate`.

  3. **Report errors/warnings as events.** This would mean complete change of the API and successful result would probably need to be reported as an event as well.

Note it would probably be good to sync the API of generated parsers with the `peg.generate` API for consistency.

Right now I’m undecided between option 1 and 3 (I don’t like option 2 because it introduces state). One small advantage of 3 is that if generated parsers also use an event system, their tracing API can be simplified. Some other pros & cons of 1 and 3 are mentioned [in this comment](https://github.com/pegjs/pegjs/issues/430#issuecomment-228912550).

**Comment by futagoza** [comment]
Going with any of the 3 options would require more work for dealing with API changes to PEG.js, but if we go with option 3 and introduce it as an option to `peg.generate`, we can still keep current API, just introduce an event emitter that listens for warnings and/or errors. See this example (done in ES6 for simplicity and omitted code (`// ...`) that does not represent the scope of this issue):

**pegjs/lib/compiler/index.js**
```javascript
const EventEmitter = require('../utils/events')
const generateAsyncParser = require('./passes/generateAsyncParser')
const generateSyncParser = require('./passes/generateSyncParser')
// ...

class Compiler extends EventEmitter {

  constructor ( options = {} ) {
    super()
    if ( options.onWarning ) this.on('warning', options.onWarning)
    if ( options.onError ) this.on('error', options.onError)
    if ( options.onComplete ) this.on('complete', options.onComplete)
    this.on('complete', ( result, options ) => {
      if ( this._events['complete'].length === 1 ) {
        if ( options.ouput === 'async' ) {
          result.output = generateAsyncParser(result, options)
        }
        else {
          result.output = generateSyncParser(result, options)
        }
      }
    })
  }
  
  compile ( ast, options = {} ) {
    // ...
    var result = { ast, /* ... */, output: /* ... */ } 
    this.emit('complete', result, options)
    // ...
    return result.output
  }

}
module.exports = Compiler
```

**pegjs/lib/peg.js**
```javascript
const Compiler = require('./compiler')
// ...

peg.generate = function ( grammar, options = {} ) {
  const config = { /* ... */ }
  // ...
  config.compiler = new Compiler(options)
  // ...
  return config.compile(config.parser.parse(grammar), options)
}
peg.buildParser = peg.generate
```

As you can see, this would allow current scripts and tools that depend on `peg.generate` or `peg.buildParser` to function without change, but at the same time introduce the event emitter that can alter the compilers output (returned result), which also allows us to move the current parser generator to a more customizable route

**Comment by Mingun** [comment]
> **Report errors/warnings as events**. This would mean complete change of the API and successful result would probably need to be reported as an event as well.

Changing API is unnecessary. See my branch [collect-all-errors](https://github.com/pegjs/pegjs/compare/master...Mingun:collect-all-errors). Default error collector may just throws `GrammarError` for errors/fatal errors and do nothing for warnings and infos. In some time in future this default behaviour can be changed to fit more progressive event-based approach. Though in this case I would suggest to use new behavior that all errors by default gathered and to provide an option in `options` for use build-in collector, implementing old behaviour: collecting by one error for time for fast migration.

**Comment by futagoza** [comment]
I've resolved reporting warnings (#327) in 851d8edfddc6a4a74de472721c67579882ced34b, but I'm unsure how to deal with errors. I'm thinking of adding 2 methods to the Session API called `fatel()` and `error()`, similar to how @Mingun did in his now-deleted `collect-all-errors` branch, but then the problem arises, what is fatel and what isn't 😕

**Comment by Mingun** [comment]
It is simple. The error because of which any further actions are senseless is fatal. All remaining -- normal. At the moment there are only normal errors

**Comment by futagoza** [comment]
Commits 851d8ed and ef05955 resolve this based on the fact that plugins can overwrite session methods, allowing use cases like multiple or limited errors (and/or warnings) to be an opt-in feature.
