### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by korczis** [pegjs/pegjs#432]
Hi,
it will be really nice to have roadmap where you share your further plans with this library. Is this possible?

PS: When do yo plan to release new version?

**Comment by ryanlin1986** [comment]
We have really heavy usage on pegjs, hope this project is still actively developed.

**Comment by hawkrives** [comment]
https://github.com/pegjs/pegjs/wiki/Roadmap

**Comment by korczis** [comment]
@hawkrives My, fault. Closing.

**Comment by ryanlin1986** [comment]
@hawkrives  Thanks, excited to see the significant performance improvement is planned.

**Comment by dmajda** [comment]
@korczis Just curious, where did you look for the roadmap? Maybe a link should to be added somewhere…

**Comment by futagoza** [comment]
@dmajda The usual place you'de find a link to docs(in this case the roadmap) is near the top in the readme, isn't it?

**Comment by dmajda** [comment]
@futagoza If anything, I’d place it into the “Development” section.
