### ISSUE TITLE
Release PEG.js 0.10.0

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#437]
The 0.10.0 release is near! Here are the remaining steps:

 * [x] Upgrade all used libraries to their newest versions
 * [x] Test Node.js support
    * [x] 0.10.x
    * [x] 0.12.x
    * [x] 4.0.x
    * [x] 5.0.x
    * [x] 6.0.x
 * [x] Test browser support
    * [x] Chrome (latest)
    * [x] Firefox (latest)
    * [x] Opera (latest)
    * [x] Safari (latest)
    * [x] Internet Explorer
      * [x] 8
      * [x] 9
      * [x] 10
      * [x] 11
    * [x] Edge (latest)
 * [x] Update `CHANGELOG.md`
 * [x] Update version to 0.10.0
 * [x] Release!

**Comment by michel-kraemer** [comment]
Let me know when you're ready and I will update the bower package immediately.

**Comment by dmajda** [comment]
@michel-kraemer Thanks! I expect 0.10.0 to go out sometime in the week of August 15–19 (I have many things going in “real life” until then).

Last time we did a coordinated release where I prepared the release, then you did the Bower package, and only then I updated the website and sent announcements. I’m not sure if this was actually worth the trouble so I’d prefer to do things more loosely this time. This means I’d do the complete release including the website update and announcements and you’d prepare the Bower package afterwards. Sounds good to you?

**Comment by michel-kraemer** [comment]
No problem. Whatever suits you.

**Comment by dmajda** [comment]
**Note to self:** I used [this script](https://gist.github.com/dmajda/9f9f9196b05d71344f4ab5a893f12d92) to help with sanity-checking that PEG.js works with various Node.js versions. For the next release this is probably worth automating (possibly by adding a complete CLI test suite).

**Comment by dmajda** [comment]
PEG.js 0.10.0 is [released](https://groups.google.com/d/msg/pegjs/8IceF13Po_w/FYK6mcCRCQAJ), closing.
