### ISSUE TITLE
Drop Node.js 0.10.x & 0.12.x support and update code accordingly

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#442]
Node.js 0.10.x & 0.12.x is obsolete and its support can be dropped (its maintenance ends in Oct/Dec 2016, see also the [Twitter poll](https://twitter.com/peg_js/status/767628930253746176)). This allows us to modernize the code a bit — mainly use some ES6 features.

Should be done after #441.

Tasks:

  * [x] Drop Node 0.10.x & 0.12.x support
    * [x] Update `package.json`
    * [x] Update the “Compatibility” section in `README.md`
    * [x] Don’t test Node 0.10.x & 0.12.x in Travis CI
  * [x] Babelify all code that can be seen by the browser
    * [x] Pass the browser version through Babel
    * [x] Pass spec code through Babel before serving it to the browser
    * [x] Pass benchmark code through Babel before serving it to the browser
  * [x] Update code
    * [x] Replace `var` with `let` & `const`
    * [x] Replace some functions with arrow functions
    * [x] Replace `classes.subclass` with native classes
    * [x] ~~Replace suitable `for` loops with `for-of`~~
    * [x] ~~Replace `Array.prototype.forEach` with `for-of`~~
    * [x] Replace remaining functions in `utils` with native ones where possible

**Comment by dmajda** [comment]
This is done now, but I’ll add two comments (both as notes-to-self and as an explanation for anyone interested):

  * **I decided to use `Array.prototype.forEach` in instead of `for-of` in the codebase.** Originally, I intended to use `for-of` because it seems more universal and more deeply integrated into the language (via [iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)). Then I prototyped the change and discovered that:

    * `Array.prototype.forEach` composes better with the rest of the code. For example, it is [possible to pass it a reference to a function which is used elsewhere](https://github.com/pegjs/pegjs/blob/b2a9dabcff19e339f32cb0dbfcffe7de15c7bcc9/lib/compiler/passes/generate-bytecode.js#L293). There is no need to spell out the actual call.

    * In at least one instance I needed an index associated with the iterated item. This is trivial with `Array.prototype.forEach` but impossible with `for-of`.

    * I don’t have much need to `break` from loops, which is the most significant practical advantage of `for-of` over `Array.prototype.forEach`. I actually think that in most cases, `break` inside a loop is a signal that your algorithm could be improved (e.g. by expressing it in functional terms).

    * A simple `for-of` loop is transpiled into quite large body of code by Babel.

  Overall, these discoveries convinced me to go the `forEach` route.

  See also [this Twitter conversation](https://twitter.com/dmajda/status/775345790277541888).

  * **I decided to get rid of `utils/arrays` and `utils/objects` modules.** Once it became possible to use `Object.keys` and array extras (enabled by dropping IE8 compatibility), the utility functions contained in these modules became less useful. PEG.js code also became somewhat inconsistent as regular JavaScript features and the utility functions started to be used next to each other. Beside, I don’t think PEG.js should be in the business of reinventing Underscore.js/Lodash.

  This change sometimes required rewriting code which used the utility functions in more low-level fashion and it introduced some small duplications, but I ended up liking the result for its simplicity and consistency.

  In the future, I may decide to adopt Lodash, but introducing it as dependency would complicate running PEG.js in the browser, which I’m not willing to do now.

**Comment by futagoza** [comment]
Since this issue was resolved, I've also dropped Node 4 support, as well as non-LTS versions of Node, which makes Node 6 the lowest version of Node that PEG.js is tested on. 

The browser bundle is generated using Rollup and Babel, with the _babel-env_ plugin's target set to IE11 now, although tbh I think I will drop IE altogether after 0.11

**Comment by Qix-** [comment]
Sounds good, that's current best practices after all. Thanks @futagoza!
