### ISSUE TITLE
Add browser-based CI

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#445]
Browser-based CI will save effort mainly during releases (so far I did manual testing in every supported browser before each release).

Probably use [Testling](https://ci.testling.com/).

**Comment by dmajda** [comment]
Another alternative is [Sauce Labs](https://saucelabs.com/) (they offer [free testing for open source projects](https://saucelabs.com/open-source)).

**Comment by dmajda** [comment]
I briefly explored [Testling](https://ci.testling.com/) and [Sauce Labs](https://saucelabs.com/):

  * Testling has the following message on its front page for some time, which disqualifies it (whether the message is true or not):
    > Testling is currently not working. We're working to fix it!

  * Sauce Labs looks somewhat difficult to setup, judging by reading the documentation and looking at the setup of projects that use it, like [Chai](https://github.com/chaijs/chai) or [Lodash](https://github.com/lodash/lodash). In particular, it would have to be paired with Travis CI.

Ultimately I concluded that while setting up Sauce Labs is doable, it’s probably not worth the time. For the time being, I’ll stick with manual browser testing before each release, which is what I’ve been doing since the very beginning. Given that historically there were almost no browser compatibility problems with PEG.js, this seems like a sufficient approach.

**Comment by dotnetCarpenter** [comment]
@dmajda Did you take a look at [Karma](https://karma-runner.github.io/1.0/index.html)? So far it has been my only successful browser based CI solution. I recently set up [svg.js](https://github.com/svgdotjs/svg.js) to use Karma and with [travis-ci cron job](https://docs.travis-ci.com/user/cron-jobs/), I plan to expand to all [browsers supported by svg.js](https://github.com/svgdotjs/svg.js#compatibility).

**Comment by dmajda** [comment]
@dotnetCarpenter Yes, I played with it. It automates some things (e.g. running the test server), but at the cost of losing in-browser feedback (the results are displayed only in the console) and additional complexity. It would probably also complicate debugging test failures.

In any case, Karma doesn’t solve the main problem, which is overall CI setup complexity. What I’d love to have is a service which would just start a test server on one machine and then look at the tests form other machines using various browsers & platforms, running the tests fully in-browser and determining whether they succeeded or not. Ideally, it would be fully integrated with GitHub (like Travis CI is) and driven by a simple config file (which would specify the commands to setup and start the test server, path to the tests, used test framework, and a browser & platform test matrix).

If you or anyone else knows about something approaching that ideal, I’d definitely want to hear about it.

**Comment by bd82** [comment]
> but at the cost of losing in-browser feedback (the results are displayed only in the console) and additional complexity.

Some tools integrate very well with the karma console output.
For example running karma tests via WebStorm/Intellij IDEA will show the results with a pretty UI inside the IDEA. Although I do agree that there could be nicer base UI to see the status of the tests in the browser. 

What I did in one project was: had the same set of tests written using mocha testing framework.
But two different runners, a Karma runner for CI related tasks (although many developers just debugged Karma directly from their IDE). and a separate "html runner"
which ran the Mocha's built it UI HTML runner for manual testing/debugging.
http://mochajs.org/#html

> It would probably also complicate debugging test failures.
Not really, to manually debug a failing test in karma, you:

- make sure only the failing test will run (in mocha: **it.only()**) 
- start karma (but with singleRun = false)
- click on the big debug icon on to right corner (or just open to http://localhost:9876/debug.html)
- set breakpoints in developer tools
- debug
- click refresh (F5) to re-run the failing test.


> In any case, Karma doesn’t solve the main problem, which is overall CI setup complexity. What I’d love to have is a service which would just start a test server on one machine and then look at the tests form other machines using various browsers & platforms, running the tests fully in-browser and determining whether they succeeded or not. Ideally, it would be fully integrated with GitHub (like Travis CI is) and driven by a simple config file.


Yes it is complex and annoying to actually get working initially. but what you are describing is actually something karma does or is part of.

* Karma starts a static web server that hosts the resources (including the tests). this is our **"test server"**
* Normally karma will launch local browsers to connect to the "test server". However, if you use the Karma Sauce Labs launcher plugin, these local browsers can be replaced by many different types of remote browsers ( that are running on the SauceLabs infrastructure).
* SauceLabs is fully integrated with github, so the only missing thing is the "entry point" to get these browser tests started.
* CI As A Service products such as Travis support a build matrix, so if you have a build task (grunt/gulp/npm scripts) that starts the browser testing, just call it from one element in the travis build matrix.

I will post links to a full working use case later.

**Comment by bd82** [comment]
* [karma configuration](https://github.com/SAP/chevrotain/blob/13ec0ac837012353a87291e8d8b6d563a4b46409/karma_sauce.conf.js) which uses sauce Labs launcher.
* [Grunt Task](https://github.com/SAP/chevrotain/blob/13ec0ac837012353a87291e8d8b6d563a4b46409/gruntfile.js#L80) to launch these karma runner during CI.
* [Travis matrix element](https://github.com/SAP/chevrotain/blob/13ec0ac837012353a87291e8d8b6d563a4b46409/.travis.yml#L26) to launch the grunt task during CI
  - note that it is in "allowed failures" section as there are sometimes random false failures.
    May be related to additional complexity of my configuration.
* [Status on Sauce Labs](https://saucelabs.com/u/shahars)
* [Build results on Travis](https://travis-ci.org/SAP/chevrotain/builds/177804281)

**Comment by dmajda** [comment]
@bd82 Thanks for all the details.

As I said above, the issue is that this is probably just not worth the time. I spend maybe 2 hours/year by manual browser testing. Just understanding and setting up the whole thing would probably take longer (even if I just review a setup done by someone else). If you add maintenance of multiple moving parts over time to the equation and consider the fact that historically there were almost no browser compatibility problems with PEG.js, the picture become crystal clear.

**Comment by bd82** [comment]
👍 

Reminds me of a funny quote by Terence Parr (creator of Antlr):

> "Why Program by Hand in Five Days what You Can Spend Five Years of Your Life Automating?"
