### ISSUE TITLE
Don’t generate code in bytecode generator

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#450]
In [various](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/passes/generate-bytecode.js#L204) [places](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/passes/generate-bytecode.js#L300) [in](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/passes/generate-bytecode.js#L537-L548) [the](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/passes/generate-bytecode.js#L565) [bytecode](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/passes/generate-bytecode.js#L601-L608) [generator](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/passes/generate-bytecode.js#L618) we actually generate code. This is conceptually wrong and it makes it harder to write non-JavaScript backends for PEG.js (it is not enough to replace the code generator, the bytecode generator needs to be modified too).

Let’s make sure the bytecode generator doesn’t generate a single piece of code.

**Comment by Mingun** [comment]
This is implemented in 9b90fa1d8168878bcaef06be57e5d1f27489743c and can be closed
