### ISSUE TITLE
Improve AST visitor definitions

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#451]
Right now, AST visitors are closure-based and they are defined using a [simple helper](https://github.com/pegjs/pegjs/blob/2a6a058c9c918dcbd615a7fff7464c1e73cce765/lib/compiler/visitor.js). After converting the codebase to ES6 I think it would be better to make them class-based (i.e. more similar to classical visitor pattern). I imagine implementing something like the [`ASTVisitor` base class](https://github.com/juttle/juttle/blob/21b49f96a0e0b2098de1673c3645a6cb673ea5a8/lib/compiler/ast-visitor.js) I wrote when working on [Juttle](https://github.com/juttle/juttle).

Note that support for building AST visitors isn’t necessarily PEG.js-specific and it could be split into a separate project. A suitable one may even already exist.

**Comment by gsun** [comment]
I implemented this in https://github.com/gsun/pegjs, and revise all the passes with this pattern.
