### ISSUE TITLE
0.10 pegjs.buildParser is not a function

### ISSUE THREAD

**Issue by lianyi** [pegjs/pegjs#456]
while updating from 0.9 to 0.10,  I got the following error 

**pegjs.buildParser is not a function**

Is this expected for upgrading from 0.9 to 0.10?

**Comment by dmajda** [comment]
@lianyi Yes, see the [relevant section of `CHANGELOG.md`](https://github.com/pegjs/pegjs/blob/v0.10.0/CHANGELOG.md#0100).

**Comment by lianyi** [comment]
thanks！ since pegjs is following SemVar versioning and this change is not backward compatible, perhaps either bump the major version or add a alias to the deprecated function?

**Comment by hawkrives** [comment]
@lianyi Semver rules for pre-1.0 projects are a bit different; generally, `0.X` is treated as what would be a major version in post-1.0 versioning. 

Possibly relevant links: [How should I deal with revisions in the 0yz initial development phase?](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase), [relevant spec point](http://semver.org/#spec-item-4)

(Apologies for the drive-by comment.)

**Comment by lianyi** [comment]
Thanks @hawkrives !  Indeed major version zero is fine with unstable public APIs by SemVar definition.  Will figure out how npm pickup the incompatible updates in this case.
