### ISSUE TITLE
Improve development documentation

### ISSUE THREAD

**Issue by dmajda** [pegjs/pegjs#457]
Document the need to do `npm install` first, how to run tests and benchmarks (this is now described in separate `README.md` files), what various build tasks do, etc.

**Comment by futagoza** [comment]
For now I've added a simple [contribution sub-section](https://github.com/pegjs/pegjs#contribution) to the [development section](https://github.com/pegjs/pegjs#development) in the README.md

Will look into adding a more detailed guide later on.
