### ISSUE TITLE
pegjs.org down

### ISSUE THREAD

**Issue by drobertson123** [pegjs/pegjs#462]
btw, thanks for the work on this. It has been very useful to me.

Sorry to do this here, but I wasn't sure where to send you a note. pegjs.org has been down for a day or two, possibly more.

http://pegjs.org/

`Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.7 (Ubuntu) Server at pegjs.org Port 80`

**Comment by dmajda** [comment]
Thanks for letting me know, the site is back online now. It looks like it was a victim of ongoing attack against another site hosted at the same VPS as pegjs.org. I tried to mitigate the attack this morning (CEST) but apparently I wasn’t completely successful. Trying additional countermeasures now.

**Comment by drobertson123** [comment]
Good luck and thanks for the efforts you are putting in.
