### ISSUE TITLE
Provide array of possible string values dynamically

### ISSUE THREAD

**Issue by Vineeth-Mohan** [pegjs/pegjs#463]
Say , i want a query parser which parses the following

```
   Give me all jobs around location names $CITY$
```
Here $CITY$ can be any city name. Rather than statically putting all the names in the grammer file , is there anyway we can provide this over the parser function. like

```
parser.parse(text , CITY_array)

**Comment by Mingun** [comment]
Use semantic predicate:
```
city = '$' name:$(!'$' .) '$' &{ return options.cities[name]; } { return name; };
```
Call:
```js
parser.parse(text, { cities: CITY_array }):
```

**Comment by dmajda** [comment]
@Vineeth-Mohan What @Mingun says. Next time please ask at the [Google Group](https://groups.google.com/forum/#!forum/pegjs), issues are for reporting bugs and requesting features. Thanks!
