### ISSUE TITLE
Epsilon Rule

### ISSUE THREAD

**Issue by shouya** [pegjs/pegjs#467]
pegjs is currently lack of a rule that eats no input and always successes (known as ϵ).

This rule can be useful for removing left recursion.

For example, the left recursion issue in:

    A = A | A a | A b

Can be resolved by rewritten as:

    A  = a A' | b A'
    A' = A A' | ϵ

This feature can be added through a special `EPSILON` rule or by allowing empty rule clauses.

**Comment by shouya** [comment]
This should be essentially equivalent to the empty string rule `''`.

**Comment by Jamesernator** [comment]
Is there a situation where the rule `e = ""` is insufficient?

It works for the above case:

```
A 
    = 'a' A_
    / 'b' A_

A_ 
    = A A_ 
    / e

e = ''
```

**Comment by shouya** [comment]
`e = ''` is indeed sufficient.

I will prefer defining `e = !. / &.`, since by default it produce an `undefined` instead of an empty string.

**Comment by dmajda** [comment]
@shouya In PEGs, one typically eliminates left recursion using repetition operators (`*` and `+`). Your example could be written in PEG.js like this:

```pegjs
A = (a / b)*
```

The existence of `*`, `+`, and `?` operators means epsilon is much less useful than in conventional grammars. For this reason I don’t think it’s worth adding it to PEG.js. I consider `""` a sufficient workaround for the rare cases where something like it is really needed.

As for empty rules (or empty sequences, to be more precise), these were allowed in previous versions but confused users, so I [removed them](https://github.com/pegjs/pegjs/commit/df154daafb9c6c952351493af02d3a55e0b05c59).
