### ISSUE TITLE
Explain subscripts in the online demo in the docs

### ISSUE THREAD

**Issue by valtih1978** [pegjs/pegjs#468]
I see a code like `tail:(_ ("*" / "/") _ Factor)`

What are those subscirpts? I cannot anything about them in the "documentation".

**Comment by hawkrives** [comment]
Which symbol or part of the code snippet are you referring to as subscripts? Just so we're talking about the same thing here.

**Comment by valtih1978** [comment]
1. What is _ if not subscript. I have just realized that these are grammar-specific whitespaces, specified in the end of the screen. Actually, I recall that parser combinators had a nice treatment of them. You specify the bottom tokens at with the regexp and the rest of whitespaces is stripped away automatically. You do not need to specify the _ all over your grammar. 

2. How are you talking about the same thing if you do not have the clue?

**Comment by dmajda** [comment]
> What is _ if not subscript.

@valtih1978 The `_` character is usually called “underscore”. A subscript is something different.

> How are you talking about the same thing if you do not have the clue?

@valtih1978 The point of @hawkrives’s comment was to *ensure* you are both talking about the same thing.

Please stay polite when engaging in PEG.js-related discussions. Rudeness is not tolerated here. Thank you.
