### ISSUE TITLE
Keywords option into grammar

### ISSUE THREAD

**Issue by valtih1978** [pegjs/pegjs#470]
I have just [made a workaround](https://groups.google.com/forum/#!topic/pegjs/jnFIAfFUXuc) for adding the keywords automatically into the grammar, just before the generate:

`peg.generate(grammar + keywords)`

The keywords is just a list of words, that I specify in a basic string "for while if do enum", which is split and 

kword = "kword"

lines, added to the grammar. This allows me to use them in my grammar without any pesky quotation marks, I can write

> program = declarations begin statements end

It like enforces that begin, end and other variables are defined somewhere instead of stupid 

> program = declarations "begin" statements "end"
> procedure = "while" pared(cond) curled("begin" statements "end")

which also sound like unrelated instances. That is, if you have `end` variable, it is defined once but strings `"end"` in one rule and `"end"` in the other are just strings and may diverge.

Moreover, this gives me kw enum in my js code, like `parse("begin", kw.begin)` says to parse "begin" with kw.begin. Here, kw.begin saves me from the same pesky quotation marks, gives some highlighting in the js editor. You could build the keywords from a string when generating the parser: `parser = peg.generate(grammar, {kwords: "for if when ..."})` so that I could get them with `kw = parser.kwords`. 

I believe that keywords appear in every program so stating/knowing them explicitly instead of buring them into the grammar, which gives a lot of work to the developer, is always worth to do.

Actually, you could introduce the `parser.rules` collection as well so that I could `const rules = parser.rules; rules.int("123")` which would call `parser.parse("123", "int")` if there is [startable](https://github.com/pegjs/pegjs/issues/469) `int` rule in the grammar. That is, you could convert your grammar rules into parsers and expose them for the users to use in place of your single root parser.

**Comment by YemSalat** [comment]
Sorry, I don't thinkI understand what you are proposing. Why not just define your keywords as part of the grammar itself? (e.g. `begin = "begin"` which seems to do exactly what your custom solution does)

**Comment by valtih1978** [comment]
> Sorry, I don't think I understand what you are proposing. Why not just define your keywords as part of the grammar itself? (e.g. begin = "begin" which seems to do exactly what your custom solution does)

Why to have the parametric rules? With parametric rules you achieve what our "repeat ourselves" custom grammars achieve, nothing more. Why bother, why do not repeat ourselves? Just to recap, `pet.generate(grammar, {kwords: "kw1 kw2 kw3 ..."})` eliminates the coding redundancy that I currently have in my "custom" grammar

```
kw1 = "kw1"
kw2 = "kw3"
kw3 = "kw3"
...

In your "custom" grammar, you repeat every keyword (and I have dozens of them) twice and copy-paste quotes around the second entry of the keyword. **This is redundancy**. Read about DRY principle and you will understand what I mean and become a better programmer.

Moreover, as long as I am recaping, my approach will give you the enum of your keywords in your JS code. This improves coherence of your code. Some idiots offer [parametrization of the rules](https://github.com/pegjs/pegjs/issues/466#issuecomment-258319744) to be able to crap like 

```
Keyword(word) = word ![a-zA-Z]+ // Matches keywords that isn't a prefix of another word
Function = Keyword("function") ...
YieldExpression = Keyword("yield") ...
```

I guess that is because they want a list of their keywords. They mark some rules with "keyword" attribute with copy-paste. I offer a way how can you  achieve the same eliminating any keywords-related copy-paste whatsoever.

**Comment by Jamesernator** [comment]
I'm not convinced your proposal would necessarily be useful widely, because in order for a keyword to be nicely parsed you need to ensure its not followed by an identifier continuation.

To demonstrate an example of where this would fail take a keyword being followed by an identifier continuation:

```
ReturnStatement
    = return _ Expression

Expression
    = (Number / Identifier) (_ "+" _ Expression)?
    / "(" _ Expression _ ")"
    / YieldExpression

YieldExpression
    = yield _ Expression

Number
    = [0-9]+

Identifier
    = [_a-zA-Z] [_a-zA-Z0-9]+

// Optional whitespace
_ = [ \t\r]*

return = "return" // automatically inserted
yield = "yield" // automatically inserted
```

This production rule would incorrectly now accept the string `returncats` as a ReturnStatement, it would also accept `return3`, `return_`, etc even though virtually every language would instead have parsed that as a lone Expression.

In order to fix that now you'd need

```
ReturnStatement
    = return ! [_a-zA-Z0-9]+ _ Expression

Expression
    = (Number / Identifier) (_ "+" _ Expression)?
    / "(" _ Expression _ ")"
    / YieldExpression

YieldExpression
    = yield ! [_a-zA-Z0-9]+ _ Expression

Number
    = [0-9]+

Identifier
    = [_a-zA-Z] [_a-zA-Z0-9]+

// Optional whitespace
_ = [ \t\r]*

return = "return" // automatically inserted
yield = "yield" // automatically inserted
```

which is clearly going to be repetitive anyway, and if your definition of identifier changes to now include unicode characters or something every single one of those `[_a-zA-Z0-9]+` productions is gonna have to change now too.

So simply inserting the rules `<keyword> = "<keyword>"` won't work because the definition of a keyword will necessarily dependent on other productions in the grammar (generally Identifier but other productions might affect it too).

---

If you want DRY with keywords you'll probably want some form of list mapping production

```
%  = "%" ! [_a-zA-Z0-9]+ <= [
    "for", 
    "while", 
    "do", 
    "enum", 
    ...
]
```

---

Also why would one want the keywords to be passed in as an argument to the parser, almost always keywords are a static form (e.g. they can't simply be replaced and not including them in the grammar has now made an incomplete grammar). Effectively what you've done is tied the grammar to the peg.generate invocation which means if someone were to take your grammar file and try to run it themselves they'd need to know (or infer) all the keywords in your file before they could even use it.

If you really want to tie keyword generation to the invocation you might as well just use this:
```
let grammar = ... // load incomplete grammar from somewhere
let keyword_productions += 'for while do...'
    .split(' ')
    .map(keyword => `${keyword} = "${keyword}"`) // or any production you like
    .join('\n')

grammar += '\n' + keyword_productions

peg.generate(grammar)
```

**Comment by valtih1978** [comment]
I agree on both points, that we need to treat keywords as special identifiers to eliminate unwanted suffices and it is a bad idea to specify keywords in a separate file. But, you are going to treat your keywords identically and you can do that if you specify them separately, if you add them separately to your grammar, rather than having to copy-paste  the same keywords boilerplate all over your grammar. 

> If you really want to tie keyword generation to the invocation you might as well just use this:

This is what I did in fact initially. But, I also wanted this boilerplate to separate and add keywords to the grammar to be done by generator because this eliminates the boilerplate for keywords that anyone needs anyway. 

So, your argument is that we can extend our grammar with keywords handlers ourselves, as part of our own preprocessor we do not need the peg support. Probably you are right. I don't know. I am recalling that in Scala combinators experience, I matched the keywords by first requesting an identifier match and then checked if that is one of our enumerated keywords. That is, it seems that I resorted to the semantic level (in combinators, your grammar is specified right in the code, so you do not feel like keywords enum is separate from grammar).

**Comment by dmajda** [comment]
> Some idiots offer parametrization of the rules to be able to crap like

@valtih1978 Ad-hominem attacks are over the line. If you want to discuss here, be polite. Consider this the last warning — if you’ll continue in this style, the next step will be a ban.

**Comment by dmajda** [comment]
I’m not going to add an option to specify keywords to `peg.generate`. The reasons are:

  1. **This is too narrow of a use case.** While the current way of defining rules for keywords is a bit repetitive, the repetition is straightforward, it is unlikely to lead to problems, and generally it feels like not enough of a problem to warrant a solution.

  2. **It moves keywords out of the grammar.** As pointed out by @Jamesernator, this doesn’t make much sense. Any viable solution needs to be in-grammar.

Note this is an instance of a classic problem many DSLs face — usual programming abstractions that help to get rid of repetition are missing. An attempt to implement them often ends up badly (see e.g. XSLT). Being aware of this danger is one reason I tend to keep PEG.js simple even at the cost of occasional repetition in grammars.
