### ISSUE TITLE
Javascript example performance issue

### ISSUE THREAD

**Issue by Reuvenc** [pegjs/pegjs#472]
Hi,

I'm using javascript example under examples folder, and encountering a weird behaviour.
Parse time is growing exponentially when adding extra brackets.

For instance, the following are the time results of parsing: 

``` javascript
2+2  // 30ms
(2 + 2) // 48ms
((2+2)) // 94ms
(((2 +2))) // 431ms
((((2+2)))) // 4184ms
(((((2+2))))) // 45949ms
```

What is the reason for such growth in calculation time? 
What needs to be done in order to improve it?

Thanks in advance,
Reuven.

**Comment by dmajda** [comment]
For the record, this looks like a duplicate of #205.
