### ISSUE TITLE
why can't this be parsed?

### ISSUE THREAD

**Issue by aleksey-bykov** [pegjs/pegjs#487]
@dmajda

gammar
```
// from RFC 2396
domainlabel = 'a' / ('a' ('a' / '-')* 'a')
```

input
```
aa
```

can't parse, why?

**Comment by gguerreiro** [comment]
The rule `('a' / '-')*` will try to match the longest string possible, so it will match 'aa' leaving no chars.

RFC 2396 domainlabel rule can be rewritten as

```
domainlabel = $([a-zA-Z] [a-zA-Z0-9]* ('-'+ [a-zA-Z0-9]+)*)
```

Also, take a look at [https://pegjs.org/documentation#grammar-syntax-and-semantics-parsing-expression-types] to check the rules PEG.js supports.

**Comment by aleksey-bykov** [comment]
thanks
