### ISSUE TITLE
Add a Header Comments Option

### ISSUE THREAD

**Issue by cyborgx37** [pegjs/pegjs#491]
Currently, the generated comment at the top of every parser is:

    /*
     * Generated by PEG.js 0.10.0.
     *
     * http://pegjs.org/
     */

In projects where the source file must be maintained and where the source and output files are in different directories, it would be helpful to have the option of adding additional comments to this header. For example:

    /*
     * Generated by PEG.js 0.10.0.
     *
     * http://pegjs.org/
     *
     * NOTE: Do not edit this file directly. Changes will be lost when rebuilding the project. Instead, edit the source file located at:
     *   <project>/src/lib/pegjs/grammars/source.pegjs
     */

This could be accomplished by adding an "extra option", like so:

    pegjs --extra-options "{ headerComments: [ \"NOTE: Do not edit this file directly. Changes will be lost when rebuilding the project. Instead, edit the source file located at:\", \"  <project>/src/lib/pegjs/assets/sourcefile.pegjs\" ] }" -o js/core/assets/parser.js /core/formulaParser.js lib/pegjs/source.pegjs

Note that the header comments are incorporated into the standard PEG.js header and are automatically formatted with the prefixed `     * `.

**Comment by cyborgx37** [comment]
I am willing to submit a pull-request to support this feature, if approved.

**Comment by futagoza** [comment]
@cyborgx37 Go for it mate, but if you can't, it's fine, I'll get the feature in by 0.11

**Comment by felix9** [comment]
I'm thinking pegjs should always generate a comment like "don't edit this, edit X instead".

Is there a use case for other comments in the generated parser?

**Comment by tilgovi** [comment]
I am using this library in apache/incubator-annotator and will need to ensure that the ASL 2.0 license header is included in everything that ships in a release. That probably includes the parser we are generating using pegjs.

**Comment by futagoza** [comment]
Implemented and released in the dev package: https://github.com/pegjs/pegjs#latest
