### ISSUE TITLE
Cannot return "{"

### ISSUE THREAD

**Issue by MayamaTakeshi** [pegjs/pegjs#498]
This doesn't work:
```
escapedOpenBracket = "\\{" { return "{" }
```
It fails with:
```
Line 1, column 28: Expected "!", "$", "&", "(", "*", "+", ".", "/", "/*", "//", ";", "?", character class, code block, comment, end of line, identifier, literal, or whitespace but "{" found.
```
So for now I am using:
```
escapedOpenBracket = "\\{" { return String.fromCharCode(0x7b) }
```

But i suppose my original expression should be valid.

**Comment by YemSalat** [comment]
There is a "bug" with the parser, but it is mentioned in the documentation:
> Curly braces in the initializer code must be balanced.

So your example will work if you tweak it a bit by adding a closing bracket:
`escapedOpenBracket = "\\{" { return "{"  /*}*/ }`

**Comment by MayamaTakeshi** [comment]
Ah, OK.
But actually, in my case, the proper doc section is:
> Curly braces in the action code must be balanced.

Thanks.
