### ISSUE TITLE
possible issue with dependency and global variable

### ISSUE THREAD

**Issue by sudodoki** [pegjs/pegjs#499]
Hi!
Thanks for pegjs, it's great.
Examining `--dependency` capabilities to possibly extract shared helpers code declared at top of the grammar. Running following command (using lodash dep for clarity)
```
pegjs --format umd --export-var queryParser --dependency lodash -o src/queries-parser.js queries.pegjs
```
I get following output head
```js
(function(root, factory) {
  if (typeof define === "function" && define.amd) {
    define(["lodash"], factory);
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory(require("lodash"));
  } else {
    root.queryParser = factory(); // ← this one of interest here
  }
})(this, function(lodash) {
```
But `lodash` would be undefined and shadow `window.lodash`. I can assume `root.queryParser = factory();` should be `root.queryParser = factory(root.lodash);` (like [here](https://github.com/umdjs/umd/blob/master/templates/returnExports.js#L27-L28) - and that change would need to be done [here](https://github.com/pegjs/pegjs/blob/266f17d11c772b6af334a6e2db63f71ce1b0fbf1/lib/compiler/passes/generate-js.js#L1339)). 
It will still require workaround since lodash would use `_` as global var. User would be doing `window.lodash = window._` before including peg.js but after including lodash
Another solution would be modifying dependencies to not only include module names, but export vars for those.

What would be your opinion on this?
I'm forced to use generated grammar in commonjs env for tests and one project and as global var in another, older project.

**Comment by futagoza** [comment]
When using `--dependency` you can use a `:` to set "varName:depSrc", so your cli command should be `pegjs --format umd --export-var queryParser --dependency _:lodash -o src/queries-parser.js queries.pegjs`

As for the shadow issue, I'll sort it out by the next release, thanks for pointiing it out.

**Comment by sudodoki** [comment]
:bow:

**Comment by futagoza** [comment]
@sudodoki  I just pushed a commit that adds the simple fix, sorry it took so long.

To get the latest version (which includes the fix), see https://github.com/pegjs/pegjs#latest
