### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by photopea** [pegjs/pegjs#501]
I wanted to use peg.js to parse Javascript files. I decided to use this grammar: https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs

It takes 20 seconds to parse a 5kB JS file (both with parser object and parser code saved & loaded afterwards).  Can I make it faster by writing a "more efficient" grammar? Or the problem in peg.js itself? I am starting to have a feeling, that fast parsers must be written manually :(

**Comment by stanleyelliott** [comment]
Have you had a look at [esprima](http://esprima.org) or [acorn](https://github.com/ternjs/acorn)? They might suit your needs better.

**Comment by photopea** [comment]
Yes, I have discovered acorn :) It can parse 1.2 MB file in 0.5 seconds! So I will use it instead, thanks!
