### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by auvipy** [pegjs/pegjs#504]
there isn;t any release in 2017. lot of commits to master since the version 0.10 last year

**Comment by futagoza** [comment]
I'm currently reviewing and planing on how to proceed, but I'm hoping to get 0.11 out by September/October 2017.

In the meantime, if you are using PEG.js as a Node.js module, you can either use the NPM module [pegjs-dev](https://www.npmjs.com/package/pegjs-dev) or use the PEG.js repository directly by adding `"pegjs": "pegjs/pegjs"` to your dependencies list in `package.json`.
