### ISSUE TITLE
emoji support?

### ISSUE THREAD

**Issue by devnewton** [pegjs/pegjs#505]
Is there a way to parse emojis with pegs?

**Comment by jayk** [comment]
Hi @devnewton,

You can already do that.  Emoji's are unicode characters, and I have a couple of pegjs grammars that use unicode (specifically math symbols in my case)  You can see the unicode for different emoji here:

http://www.unicode.org/emoji/charts/emoji-list.html

**Comment by futagoza** [comment]
@devnewton Since @jayk has answered your question correctly, I'm closing this issue 😄
