### ISSUE TITLE
https://pegjs.org/ is down

### ISSUE THREAD

**Issue by dstockwell** [pegjs/pegjs#508]
I haven't been able to access it for over a day.

**Comment by mikeaustin** [comment]
traceroute to pegjs.org (13.56.97.223), 64 hops max, 52 byte packets
 1  192.168.0.1 (192.168.0.1)  1.971 ms  2.138 ms  1.295 ms
 2  96.120.88.185 (96.120.88.185)  10.474 ms  22.839 ms  26.475 ms
 3  te-0-6-0-13-sur04.sanmateo.ca.sfba.comcast.net (68.85.101.41)  68.999 ms  17.345 ms  13.174 ms
 4  68.85.155.93 (68.85.155.93)  24.676 ms
    hu-0-4-0-0-sur03.sanmateo.ca.sfba.comcast.net (68.85.155.221)  20.596 ms
    68.85.155.93 (68.85.155.93)  83.846 ms
 5  be-218-ar01.santaclara.ca.sfba.comcast.net (69.139.199.197)  11.131 ms  20.265 ms  13.054 ms
 6  be-33651-cr02.sunnyvale.ca.ibone.comcast.net (68.86.90.93)  15.225 ms  38.992 ms  16.908 ms
 7  be-11083-pe02.529bryant.ca.ibone.comcast.net (68.86.84.14)  20.528 ms  32.784 ms  22.649 ms
 8  as16509-2-c.529bryant.ca.ibone.comcast.net (66.208.229.30)  19.820 ms  19.233 ms  12.313 ms
 9  * * *
10  * * *
11  205.251.230.120 (205.251.230.120)  20.892 ms
    72.21.222.220 (72.21.222.220)  26.033 ms  27.756 ms
12  * * *
13  * * 

PING pegjs.org (13.56.97.223): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5

**Comment by futagoza** [comment]
The [pegjs.org](https://pegjs.org/) domain is currently in the middle of a tranfer from the domain registrar for @dmajda to mine. It currently resolves to `alias.zeit.co`, which according to ZEIT's documentation:

> If your DNS of choice doesn't support those record types, you might temporarily resolve alias.zeit.co and use one of the returned IP addresses. Please note that those might stop working after a while, so don't rely on them as a long-term solution..

Basically, the VPS I'm using the the Node.js website on is using a dynamic IP address to serve it's content via the [pegjs.org](https://pegjs.org/) domain, but once the transfer is complete (which is currently estimated to occur on or after 25 June 2017) I will setup the nameservers correctly so this doesn't effect the domain.
