### ISSUE TITLE
Dynamically generate / parse rules based on configuration

### ISSUE THREAD

**Issue by vidushigupta** [pegjs/pegjs#512]
I am new to Peg.js & have written a grammar which is similar to 'Lucene Query Grammar for PEG.js'  https://github.com/polyfractal/elasticsearch-inquisitor/blob/master/_site/js/vendor/lucene/lucene-query.grammar. 
The grammar is working good. 
The next level of feature that I need to add is to be able to have a parser that dynamically understands the configuration, hence be able to parse based on rules that are different based on multiple configurations as per need. For example - the rule looks like 

logicalOperator
  = 'OR'i![a-zA-Z0-9_] 
  / 'AND'i![a-zA-Z0-9_]
  / 'NOT'i![a-zA-Z0-9_]

But what I need is based on app config, I should only need a rule that will parse for first two expressions or may be last two as correct logical operators to validate against. The list of correct operators I am passing using options during parse time.

1. What are my options to achieve this feature of dynamic rules?

2. Related question-  is there a way to send the custom objects in parser during generation & be able to use in grammar.

Any suggestions are much appreciated !!

**Comment by Mingun** [comment]
This is pretty easy:
```pegjs
logicalOperator
  = r:$unit+ &{ return options.keywords.indexOf(r.toLowerCase()) >= 0; } { return r; }
unit = [_0-9a-z]i;
```
Use as:
```js
let parser = ...;
let result = parser.parse(..., { keywords: ['or', 'and', 'not'] });
```

**Comment by vidushigupta** [comment]
Wow !! it worked like a charm. 
I would say the PEG.js should have a better documentation around the predicate. There is no way, I could have guessed / understood that the solution that I was seeking for would be done using the predicate. I am sure, there are may others that have hard time understanding the constructs.

Neverthless, PEG.js is an awesome parser. @Mingun, thank you for the solution.

**Comment by futagoza** [comment]
@vidushigupta Improving the documentation is on the [roadmap](https://github.com/pegjs/pegjs/wiki/Roadmap) 😄
