### ISSUE TITLE
Using external functions in parser actions

### ISSUE THREAD

**Issue by stuhlmueller** [pegjs/pegjs#517]
I'm using pegjs in node and would like to use external functions, classes, and libraries in parser actions. Here's a minimal example:

```js
import peg from "pegjs";

class Wrapper {
  constructor(text) {
    this.text = text;
  }
}

var parser = peg.generate("start = ('a' / 'b')+ { return new Wrapper(text); }");

parser.parse("abba");
```

Of course, as is this fails with `ReferenceError: Wrapper is not defined`. Is there a way to make this work?

**Comment by jtenner** [comment]
You could try:

```javascript
//./wrapper.js
class Wrapper {
  constructor(text) {
    this.text = text;
  }
}

import peg from "pegjs";

var parser = peg.generate(`
{ let Wrapper = require('./wrapper'); }

start = ('a' / 'b')+ { return Wrapper(text); }
`);

parser.parse("abba");
```

**Comment by stuhlmueller** [comment]
This is a promising direction and works for absolute imports.

Relative imports fail though:

    Error: Cannot find module './wrapper'.

I think the reason is that node is searching in `pegjs/lib/compiler` (within `node_modules`), not in the main script directory. It's possible to construct a relative path from there to `wrapper.js`, e.g. `../../../src/wrapper.js`, and this works, but I wonder if there's a better approach.

**Comment by Mingun** [comment]
Inside the parser you have access to `options`  variable, so just use that code:
```js
let peg = require("pegjs");
 
let parser = peg.generate(
  "start = ('a' / 'b')+ { return new options.Wrapper(text); }",
  { Wrapper: Wrapper }
);
 
 parser.parse("abba");
```

**Comment by stuhlmueller** [comment]
Neat! Exactly what I was looking for:

```js
const parser = peg.generate(`
{ const { Wrapper } = options; }
start = ('a' / 'b')+ { return new Wrapper(text); }
`);

parser.parse("abba", { Wrapper });
```

**Comment by Izhaki** [comment]
@Mingun Your example doesn't seem to work (providing options in `generate`) whereas @stuhlmueller example does (providing options in `parse`).

I'd argue that it would be nice to be able to pass options to `generate`, because often what you want is provide support functions to the grammar, and not something that is parse specific. Would be nice if the second parameter given to `generate` will also have an `helpers` field that you can access in the parser.

The ability to 'inject' external functions to the parser allows a more native way (dependencies, syntax, etc.) to write JS code compared to having it in the grammar itself. Surely this is something to be documented?

**Comment by Mingun** [comment]
Yes, of course, `options` for parse stage must be passed to `parse` method. My mistake.

> Would be nice if the second parameter given to `generate` will also have an `helpers` field that you can access in the parser.

`generate` already has second parameter called `options`, but it used on parser generation phase, but parser support functions used at parser usage phase. But I understood your desire.

Я думаю, что можно добавить опцию defaultParseOptions методу generate, которая будет содержать параметры по умолчанию, передаваемые в parse если они не будут указаны в непосредственной точке вызова
  
I think that we can add a new  `defaultParseOptions` option to the `generate` method which will contain the default arguments for `parse` invocation of the generated parser. So, @ stuhlmueller  example will be looks like:
```js
const parser = peg.generate(`
{ const { Wrapper } = options; }
start = ('a' / 'b')+ { return new Wrapper(text); }
`, { defaultParseOptions: Wrapper });

parser.parse("abba");
```

But even now this can be archived with some manual settings and I think, that can be even extracted to a plugin:
```js
'use strict';

function myGenerate(grammar, options) {
  let parser = peg.generate(grammar, options);
  let parse = parser.parse;
  parser.parse = function(input, opts) {
    return parse(input, Object.assign(opts, options.defaultParseOptions || {}))
  }
}
// usage
const parser = myGenerate(`
{ const { Wrapper } = options; }
start = ('a' / 'b')+ { return new Wrapper(text); }
`, { defaultParseOptions: Wrapper });

parser.parse("abba");
```

**Comment by Izhaki** [comment]
@Mingun 

Indeed, your last proposal is exactly what I had in mind, but it is still a patch and it doesn't quite map to the 'domain model' or 'requirement' or 'user need' which is that you just want to pass helper (external) functions to the parser.

Thus, I am highly fond of your first proposal: `defaultParseOptions`.

In the meantime, would be useful if the README updates to show this can be done with `parse`?

**Comment by futagoza** [comment]
I've added support for this in 30cfa295530a17b53bd1f71202bc8effe976408a via the new `context` option that can be passed to `peg.generate`:

```js
const parser = peg.generate(`
  start = ('a' / 'b')+ { return new Wrapper(text); }
`, { context: { Wrapper } });

parser.parse("abba");
```

**Comment by ocharles** [comment]
@futagoza how does that play with generate a parser with `npx pegjs`? That is, generating parsers from standalone PEGJS files.

**Comment by futagoza** [comment]
@ocharles Currently there's no plan to add a flag/option on the CLI, but it should be simple to do via the config file (which can be passed to the CLI as `-c [filename]`), which can now be a  `.js` file.

**Comment by ocharles** [comment]
Ok, thanks - I'll look into that.
