### ISSUE TITLE
Add a TypeScript declaration file

### ISSUE THREAD

**Issue by futagoza** [pegjs/pegjs#519]
Currently the `.d.ts` file for PEG.js available at [@types/pegjs](https://npmjs.org/@types/pegjs) ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pegjs)) is okay if your just using it as part of your own program that does something else, but if you want to make a plugin or a fork of PEG.js that deals with AST's, then it quickly becomes useless.

Let's not forget about the fact that it is only valid for the current [NPM release of PEG.js](https://npmjs.org/pegjs).

- [x] Add `pegjs.d.ts`, an up to date declaration file based on [@types/pegjs](https://npmjs.org/@types/pegjs)
- [x] Add support for AST types returned by parser
- [x] Add types for passes used by the compiler
- [ ] Build a TypeScript based plugin for PEG.js that confirms the `.d.ts` file works

**Comment by polkovnikov-ph** [comment]
I was going to create this exact ticket, but it's already nicely created by you. Great job!
