### ISSUE TITLE
enhancement: use export default in es output format

### ISSUE THREAD

**Issue by frantic1048** [pegjs/pegjs#525]
I'm using latest `pegjs-dev` with es output format in [my project](https://github.com/frantic1048/Est/blob/master/loaders/pegjs-loader.js#L12).

I found it is a little not convenient when importing the parser.

```
// current we need to use `import * as`
// alternatively use .pegjs with webpack
import * as parser from './parser.js'
```

I think using `export default` could be better when importing the parser. Thus we can simply:

```
import parser from './parser.js'
```

**Comment by futagoza** [comment]
Added to generator and updated `pegjs-dev` package 😄
