### ISSUE TITLE
Reimplement offset() helper in generated parsers

### ISSUE THREAD

**Issue by felix9** [pegjs/pegjs#526]
Can we get offset() back? Use case: a parser that builds a parse tree and annotates each node with its source location. offset() is very cheap, and calling it for thousands of nodes is fine. location() is much more expensive, and using it is a noticeable performance hit.

**Comment by futagoza** [comment]
You can easily get `offset`/`line`/`column` by adding the following to the initializer:

```js
function offset() {
    return peg$savedPos;
}

function line() {
    return peg$computePosDetails(peg$savedPos).line;
}

function column() {
    return peg$computePosDetails(peg$savedPos).column;
}
```

It's been more then 2 years since this change was made, and although I don't mind adding `offset()` back in, to be honest I think it's better using `peg$savedPos` directly.

**Comment by felix9** [comment]
I'd rather not use any peg$ variables in my code, because they're not an advertised interface, so I'd expect them to disappear without warning. But I guess that's ok for now. (I'm working with a codebase that's still using pegjs 0.8 and looking at upgrading it to 0.10)

**Comment by futagoza** [comment]
Busy right now with another project, but this should be reimplemented by 0.11 😄
