### ISSUE TITLE
`error` vs `expected` function

### ISSUE THREAD

**Issue by jmeas** [pegjs/pegjs#530]
In the [`expression { action }`](https://github.com/pegjs/pegjs#expression--action-) documentation, it indicates that there are two methods you can call: expected and error.

`expected` says that it makes the parser "throw an exception." This makes me think that it errors, and my tests confirm this.

It also says there's an `error` function, which seems similar.

Is there a place that maybe has a better explanation of when to use which method? Perhaps an example that uses both could demonstrate why you might use one over the other.

Thanks!

**Comment by felix9** [comment]
`expected` is for when there's a specific syntax you're looking for, but didn't find, such as
`Expected integer but "a" found.`

`error` is for more general errors.

**Comment by jmeas** [comment]
Thanks @felix9!
