### ISSUE TITLE
'?' Can not Handle Optional Properly

### ISSUE THREAD

**Issue by wxy325** [pegjs/pegjs#536]
Hi, I want to use PEG.js grammar to match time interval second, but it seems that the question mark `?` can not work properly.

My Grammar Follow:
```
TimeInterval
  = TimeIntervalNumber 's'
  
TimeIntervalNumber
  = [0-6]?[0-9]
```

In this grammar, I want to match string that represent second (`1s`, `3s`, `30s`, `60s`), however, it seems that the question mark for `[0-6]` can not work properly. 

For, exmaple, if I match `3s`, Peg.js will reports `Line 1, column 2: Expected [0-9] but "s" found.` It seems that `[0-6]` does not become optional.

Is that a bug inside PEG.js?

**Comment by pjmolina** [comment]
I think is not a bug, but a consequence of how PEG grammars work. Try the following refactor:
```
TimeInterval  = TimeIntervalNumber 's'
TimeIntervalNumber
  = [0-6][0-9] 
  / [0-9]
```
First subrule will recognize two digits number like 59, second subrule (after failing the first one) will recognize one digit expressions.

Note that subrule order is important. Reversing them will not work.

**Comment by wxy325** [comment]
Hi @pjmolina, thanks very much for your reply!
