### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by th0r** [pegjs/pegjs#537]
Hi guys!

At first, let me thank you for an amazing piece of software! This is one of those tools that "just work" and the only thing that limits you is your imagination!

But I've noticed that the last published version (0.10) was released more than a year ago and it doesn't contain any features mentioned in the readme (e.g. `--format es`).

Do you have plans to release a new version?

**Comment by futagoza** [comment]
I do plan to release a new version. I initially planned to release **0.11** before 2018, but personal life has recently become hectic, so I've had less time to work on PEG.js, but don't worry, In the meantime you can either use the repository directly or it's npm package (`pegjs-dev`):
```JSON
{
    "dependencies": {
        "pegjs": "pegjs/pegjs#master",
        "pegjs-dev": "*"
    }
}
```

**Comment by th0r** [comment]
Got it, thanks!

**Comment by futagoza** [comment]
pegjs-dev has been deprecated in favour of a dev tagged pegjs release.
see https://github.com/pegjs/pegjs#latest
