### ISSUE TITLE
scoping of labels looks more like a breaking change rather than a bugfix

### ISSUE THREAD

**Issue by akatov** [pegjs/pegjs#540]
The 2nd Bug Fix reported in the Changelog for v0.10.0 (`Fixed label scoping so that labels in expressions like (a:"a") or (a:"a" b:"b" c:"c") aren’t visible from the outside.`) looks more like a breaking (major) change rather than a bug, at least from a user's perspective whose grammar(s) (with some extra parentheses for clearer separation of blocks) worked just fine with v0.9.x but are broken with v0.10.0 because some variables aren't bound. Do you think it' worth changing this entry's section to major changes, or at least marking it as a potentially breaking change as well as a bugfix?

**Comment by futagoza** [comment]
I always assumed that the labels were scoped to the sequence they are written in, so never even considered accessing sub-labels, but when @dmajda released 0.10 back in 2016 I was surprised that it could be done before.

I'm sure this is a breaking change if people were using this feature, but I think this is definitely a bugfix, especially if it was a feature that wasn't intended to work that way.

**Comment by futagoza** [comment]
@akatov Closing as I don't view this as an issue, but if you disagree, please state so and I'll re-open the issue.
