### ISSUE TITLE
Document the Plugin API

### ISSUE THREAD

**Issue by futagoza** [pegjs/pegjs#544]
As @mnpenner and @ming-codes [pointed out](https://github.com/pegjs/pegjs/issues/106#issuecomment-275002437), there's no documentation for the Plugin API, so:

- [ ] Add documentation for the Plugin API
- [ ] Add a simple example into the documentation
- [ ] Link to some commonly used plugins
- [ ] Add a link to [github.com/pegjs/pegjs/wiki/Plugins](https://github.com/pegjs/pegjs/wiki/Plugins)

**Comment by mnpenner** [comment]
Thanks for adding some documentation.

So, how would I inject an initializer? i.e. I just want to define a few helper functions for use throughout the grammar.

AFAICT, I'd want to [add something into `config.passes.generate`](https://github.com/metadevpro/ts-pegjs/blob/bad419b793cdbaf05b6a6437c241d35ea5c75011/src/tspegjs.js#L3-L6), but I don't want to override the entire 'generate' pass like TS did, I just want to append to the initializer. 

Can I do that with a plugin?

**Comment by futagoza** [comment]
@mnpenner Yep, you've answered your own question quite well 👍, although you might want to use `initializerSource + "\n" + ast.initializer.code;` instead of `initializerSource + "\n;" + initializerSource;` 😆

**Comment by mnpenner** [comment]
@futagoza Whoops! Good catch. Thanks!
