### ISSUE TITLE
tiny "first hour" issues from a newbie

### ISSUE THREAD

**Issue by tom-berend** [pegjs/pegjs#548]
### Issue type

* [x] Bug Report
* [x] Feature Request
* [ ] Question
* [ ] Not an issue

### Prerequisites

* [ ] Can you reproduce the issue?
* [ ] Is this an urgent issue?
* [ ] Did you search the repository issues?
* [ ] Did you check the forums?
* [ ] Did you perform a web search (google, yahoo, etc)?

For more information, see the **CONTRIBUTING** document.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example code:**

```
    An example of code related to this issue
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### System

**PEG.js:** ...
**Node.js:** ...
**NPM:** ...
**Browser:** ... 
**OS:**  ...
**Editor:** ...

**Comment by tom-berend** [comment]
the 'arithmetics' demo has 

Integer "integer"
  = _ [0-9]+ { return parseInt(text(), 10); } 

but should be 

Integer "integer"
  = _ [0-9]+ { return parseInt(offset, 10); } 

------------------

I'm trying to use the generated file in a Cordova project and the 'module' declaration causes problems.  any way to make it usable in a browser (I'm afraid this might be a real newbie question).

**Comment by tom-berend** [comment]
also, the readme says 'version 0.10.0', but the generated output says '0.7.0'

**Comment by futagoza** [comment]
Hey mate, thank's for creating the issue but next time, can you read the template and follow it 😉 

1) Using your suggestion on the online editor ([www.pegjs.org/online](https://www.pegjs.org/online)) throw's an error because `offset` is undefined, whereas `text()` works because it is an internal function of the generated parser that returns the source text between the start and end of the sequence (in this case `_ [0-9]+`).
2) I just went over the code base for `v0.10.0` and tested it but couldn't find `0.7.0` generated anywhere. Where are you installing your copy from, and how? NPM (command line or `package.json`)? Bower?

**Comment by tom-berend** [comment]
i cloned git and followed the instructions to build.  ran the test suites, all ok.  readme says 0.10.0.  but saw the 0.7.0, and then followed the instructions for NPM install. still 0.7.0.  at some point my system told me to use sudo apt-get install node-pegjs (i think when I tried running pegjs). yoiks, could that have fetched an old version from Ubuntu's library?   

after compile, arithmetics.ja starts with following lines (i'm using the command line $pegjs -e parser ...)

parser = (function(){
  /*
   * Generated by PEG.js 0.7.0.
   *
   * http://pegjs.majda.cz/
   */

now that i notice the strange Czech website, i'm wondering if somehow i did something strange with INERTIA (a Clojure compiler that uses PegJS).  I pulled it from github to look at it before I pulled PegJS, but don't believe I ran any of its files.

the parser that I am generating does NOT have a function text().  clearly I have made a mess.  Sorry about this.

**Comment by futagoza** [comment]
It's fine. I don't use Linux, but from what I can tell:

1. https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
2. `$ npm install pegjs@dev` (add a `-g` flag for global install instead of local)
3. `$ pegjs parser.pegjs -o parser.js`

**Comment by futagoza** [comment]
Closing as this doesn't seem to be an issue with PEG.js

**Comment by tom-berend** [comment]
many thanks.  playing with PegJS, amazed and delighted.  it is a clean tool, does exactly what it promises.  I'm playing with the javascript.pegjs example, and awed.

my linux problems were uglier than that, all sorts of strangeness with permissions and missing files.  but i remembered a trick from my Windows days, and rebooted.  everything worked after that.  <g>
