### ISSUE TITLE
Allow options to be passed from 'peg.generate' to the PEG.js parser

### ISSUE THREAD

**Issue by futagoza** [pegjs/pegjs#553]
As the title suggest's, this feature will allow developers to send options to the PEG.js parser when calling `peg.generate` so that they don't have to create wrapper functions to get the same behavoir:

```js
const peg = require( "pegjs" );
const phpegjs = require( "phpegjs" );

const parser = peg.generate( "start = ('a' / 'b')+", {

    plugins: [ phpegjs ],
    parser: {
        trace: process.argv.includes( "--debug" ),
        reservedWords: phpegjs.reservedWords,
    }

} );
```

This will also allow plugins (like `phpegjs` shown in the example) to set their own default's for the parser options if the developer doesn't supply one.

Roadmap:
- [x] Update `peg.generate` to create the optional `options.parser` if it dousn't exist (default value: `{}`)
- [x] Update `peg.generate` to pass `options.parser` to `config.parser.parse` when called
- [x] Move reserved words for JavaScript to `lib/compiler/js.js`
- [x] Update `src/parser.pegjs` to set reserved words from options:
  ```js
  const RESERVED_WORDS = options.reservedWords || reqiure( "./compiler/js" ).reservedWords;
  ```
- [x] Update TypeScript definitions and if needed, add tests (though I don't hink any are needed)
- [ ] Update `README.md`

Related issues:
 - #517: Using external functions in parser actions
 - #552: Improve error when reserved word used as label

**Comment by futagoza** [comment]
@Mingun This is what you were talking about in [#552](https://github.com/pegjs/pegjs/pull/552#issuecomment-355807904), isn't it?

**Comment by Mingun** [comment]
Yes. I however do not see how you assume to make available the passed options to a parser? I propose the following solution: add new variable `compileOptions`, in addition to `options`. It will hold `options` object passed to the `generate` method.

**Comment by futagoza** [comment]
Sorry, I'm not following what you mean. Are you talking about options passed from `peg.generate` to `peg.parser.parse`, or are you talking about passing options to a generated parser?

**Comment by Mingun** [comment]
I mean, that in construction
```js
const RESERVED_WORDS = options.reservedWords || reqiure( "./compiler/js" ).reservedWords;
```
`options` -- object, passed to the `parse` method. But when you write grammar your assume that `reservedWords` will be passed through options of the `generate` method at time of generation parser, not at time of parser use. With `compileOptions` this snippet will looks like:
```js
const RESERVED_WORDS = compileOptions.reservedWords || reqiure( "./compiler/js" ).reservedWords;
```

**Comment by futagoza** [comment]
I think your misunderstanding, `options.reservedWords` will be inside the PEG.js parser (`src/parser.pegjs`), but will be passed to it through `peg.generate`, so is actually `options.parser.reservedWords`.

In other words, `options.parser` won't be passed to the generated parser, but to the PEG.js parser (`peg.parser.parse`). This is so that developer's don't have to create their own version of `peg.generate` just to pass custom options to the PEG.js parser, or any custom parser a plugin may set.

As for passing options to a generated parser, I believe that shouldn't be supported by the project, as the generated parser already includes the options object.

**Comment by futagoza** [comment]
> As for passing options to a generated parser, I believe that shouldn't be supported by the project, as the generated parser already includes the options object.

Lets just say that I never said this 🙄 

@Mingun I added support for this (#517) in 30cfa295530a17b53bd1f71202bc8effe976408a, after I tried running the fixed test (see the commit) on the browser (via `npm run test:server`) but it kept failing due to the fact there is no way to pass PEG.js to it unless I add it via a script tag in the html file, but I was a stubbarn mule and refused to take that route just for one test 🤣
