### ISSUE TITLE
Automatically return match actions that are a single expression

### ISSUE THREAD

**Issue by alexchandel** [pegjs/pegjs#557]
### Issue type

* [x] Feature Request

### Description

Predicates and match actions that consist of a single expression should return the value of that expression, even if `return` is not specified. This would eliminate a lot of clutter & unnecessary characters in PEG.js grammars.

To preserve the ability to return no result in a predicate or action (for whatever reason), the `return` shouldn't be inserted if the action contains a semicolon (i.e. `{ hex(i) }` becomes `{ return hex(i) }`, but `{ why(); }` remains the same). And for simplicity of implementation, it should only be inserted in single-line statements.

This is easy to implement. Just do this:
```js
if (
  (!str.includes('\n') || !str.replace(/^\s*|\s*$/g, '').includes('\n')) && (!str.includes(';') || !str.replace(/(\/\*([^*]|\*[^\/])*\*\/|\/\/[^\n]*|"([^"]|\\")*"|'([^']|\\')*'|`([^`]|\\`)*`|\/([^\/]|\\\/)+\/)*/g, '').includes(';'))
) {
  str = 'return '+str
}
```

That regex should strip multiline and one-line comments, double- and single-quoted strings, and templates. The newline test even goes out of its way to strip preceding and trailing space so
```js
{
  hex(i)
}
```
still matches.

**Comment by futagoza** [comment]
Sorry Alex, adding this would potentially break plugins (like [pegjs-coffee-plugin](https://www.npmjs.com/package/pegjs-coffee-plugin)) and could lead to unintentional mistakes when the developer doesn't intend to return anything.

If you really want to use this syntax, you have 2 options:

1. A CoffeeScript plugin ([pegcoffee](https://www.npmjs.com/package/pegcoffee) or [pegjs-coffee-plugin](https://www.npmjs.com/package/pegjs-coffee-plugin))
2. Roll your own plugin (no documentation yet (see #544), so check out other [plugins](https://github.com/pegjs/pegjs/wiki/Plugins) )

**Comment by futagoza** [comment]
I haven't actually had to create a plugin like this myself (before or after I took-over development of PEG.js), but based on [pegjs-coffee-plugin/index.js](https://github.com/dignifiedquire/pegjs-coffee-plugin/blob/master/index.js), the basic rundown is (using PEG.js v0.10 and Node.js v4):

`src/parser.pegjs`:
```js
{
  // strips 'f' from a float number
  function stripedtext() {
    var v = text();
    return v.endsWith("f") ? v.slice(0, -1) : v;
  }
}

number = int ("." int)* "f"? { stripedtext(); }
int = [0-9]+
```

`src/pegjs/add-return-plugin.js`:
```js
"use strict";

const visitor = require( "pegjs" ).compiler.visitor;

function AddReturnStatement( str ) {

    // Your code will go here

    return str;

}

function compileNode (node) {

    if ( typeof node.code === "string" ) node.code = AddReturnStatement( node.code );

}

function compileExpression ( node ) {

    compile( node.expression );
    compileNode( node );

}

const compile = visitor.build( {
    semantic_not: compileNode,
    semantic_and: compileNode,
    literal: compileNode,
    rule_ref: compileNode,
    'class': compileNode,
    any: compileNode,
    action: compileExpression,
    rule: compileExpression,
    named: compileExpression,
    labeled: compileExpression,
    text: compileExpression,
    simple_and: compileExpression,
    simple_not: compileExpression,
    optional: compileExpression,
    zero_or_more: compileExpression,
    one_or_more: compileExpression,
} );

module.exports = {
    use( config ){

        config.passes.transform.unshift( ast => compile( ast ) );

    }
};
```

usage via CLI:
```bash
$ pegjs --plugin ./src/pegjs/add-return-plugin.js -o lib/parser.js src/parser.pegjs
```

usage via API:
```js
"use strict";

const fs = require( "fs" );
const peg = require( "pegjs" );
const plugins = [
    require( "./src/pegjs/add-return-plugin" )
];

let parser = fs.readFileSync( "./src/parser.pegjs", "utf8" );
parser = peg.generate( parser, { plugins: plugins } );
fs.writeFileSync( "./lib/parser.js", parser, "utf8" );
```

**Comment by alexchandel** [comment]
pegjs-coffee-plugin injects a return everywhere necessary, so it wouldn't break. I can't find where any other plugins would break either.

PEG.js is on version 0.10.0. Its own readme states:

> PEG.js is still very much work in progress. There are no compatibility guarantees until version 1.0

so avoiding developer confusion is as simple as adding a line in the readme's `Action Execution Environment` section stating that single-expression blocks automatically return.

In the examples I've looked at, I haven't yet seen a single PEG.js grammar that intentionally doesn't `return` in a one-expression predicate to constitutively fail a rule (excluding `error()` & `expected()` of course, but inserting `return` doesn't change that), nor one that has a single defined expression with no semicolon in an action that intentionally returns `undefined`.

I _have_ seen lots of rules that would be significantly shorter with implicit `return` for expressions, and I've also made unintentional mistakes forgetting `return`s . This seems like a safe, desirable breaking change.

**Comment by polkovnikov-ph** [comment]
@alexchandel There is [another issue](https://github.com/pegjs/pegjs/issues/545) that seems related to thise one. Would it solve your problem?

**Comment by futagoza** [comment]
@alexchandel  pegjs-coffee-plugin was just an example, but what I was trying to say was your suggestion of having an internal pass that transforms the content of the code block could cause problems if the developer is planning on pushing **all code blocks** in _thier grammar_ through a different plugin that does god knows what to the contents of the code block, espesially if it is not JavaScript (e.g CoffeeScript, PHP, C++, etc)
