### ISSUE TITLE
Parse javascript?

### ISSUE THREAD

**Issue by bgnx** [pegjs/pegjs#563]
### Issue type
* Question

### Description
Can pegjs grammar represent current javascript grammar? Is there any up to date (or just existing) pegjs grammar for javascript?

**Comment by futagoza** [comment]
You mean PEG.js generated parser that can parse ES2018+ JavaScript? Not that I'm aware of, no. But once Stage 1 of #523 is done, it's one of the things I want to get around to doing.

**Comment by lauriro** [comment]
how about [example](https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs)?

**Comment by bd82** [comment]
> how about example?

I think that is **not** a modern (ES2017) ECMAScript grammar.
But could be used as a basis to build upon.

I did try to use this example ES5 grammar but it seems to have kind of choked on anything but very small inputs. So I recommend including a small performance test if/when such a grammar is implemented.
