### ISSUE TITLE
Parametrized text separator

### ISSUE THREAD

**Issue by xduseko** [pegjs/pegjs#565]
### Issue type

- **Question**

### Description

Is it possible to create parameterized text separator passed through options?

Consider example grammar:
```
Literals
  = string1:Literal strings:(Separator Literal)* {
    return strings.reduce(function(array, record) {
      return array.concat(record[1]);
    }, [string1]);
  }

Literal
  = char:(!Separator Character)+ {
    return char
      .map(function(x) {
        return x[1];
      })
      .join('');
  }

Separator
  = "--"

Character
  = .
```

There is `Separator` that have to be excluded from `Literal`. I would like to have it configurable.

I have managed to read it from options, but I don't know how to consume variable character length. Example bellow is working for every separator composed from 2 characters. But what if someone pass 3 characters?

```
{
  options.separator = options.separator || '--';
}

Literals
  = string1:Literal strings:(Separator Literal)* {
    return strings.reduce(function(array, record) {
      return array.concat(record[1]);
    }, [string1]);
  }

Literal
  = char:(!Separator Character)+ {
    return char
      .map(function(x) {
        return x[1];
      })
      .join('');
  }

Separator
  = chars:(. .) & {
    return chars.join('') === options.separator;
  }

Character
  = .
```

**Comment by Mingun** [comment]
You can use [my fork](https://github.com/Mingun/pegjs) with such `Separator` rule:
```
Separator = len:({ return options.separator.length; }) s:$.|len| &{ return s === options.separator; };
```

**Comment by xduseko** [comment]
Does it mean it's impossible without modifying PEG.js source code for sure?

**Comment by Mingun** [comment]
No it is possible, just more boilerplate. You can implement range in current terms, something like:
```
{let count = ...;}
List = $(. &{ return count-->0; })
```
but do not forget about backtraking.

**Comment by xduseko** [comment]
Thanks, it's working!

**Comment by futagoza** [comment]
As I'm assuming the question is answered, closing.
