### ISSUE TITLE
Match from set of string literals

### ISSUE THREAD

**Issue by MegaArman** [pegjs/pegjs#573]
### Issue type

- **Bug Report:** 

### Description
I would expect a rule like  `animal = "cat"/ "catdog"/ `to not return an error for input literal "catdog"

Here's what I found online:
[https://stackoverflow.com/questions/44226562/match-the-string-literal-containing-underscope-using-peg-js](url)
Matching a substring of a literal is not matching a literal. I don't understand why that asker had to reorder his rule for it to work as he expected. Is there an easy way to specify a literal must match based on a set of literals using peg.js? It seems very bug prone to have to order more than a few string literals.

**Comment by pjmolina** [comment]
Hi.
This is not a pegjs bug. But a requirement in PEG: That how the algoritm works. 

See the original paper or [slide 16](http://bford.info/pub/lang/peg-slides.pdf)
'prioritized choice with backtracking'

**Comment by MegaArman** [comment]
I understand the order of productions matters in a PEG, but PEG.js claims it can "Match exact literal string and return it". It is not checking for literals by anyone's definition if "catdog" passes the literal "cat" - that's more akin to regex, correct?

**Comment by pjmolina** [comment]
In the same [documentation](https://pegjs.org/documentation) page, you already have the doc for the prioritized choice rule:

`expression1 / expression2 / ... / expressionn`
*Try to match the first expression, if it does not succeed, try the second one, etc. Return the match result of the **first successfully matched** expression. If no expression matches, consider the match failed.*

It looks like you are expecting same semantics in PEG's `/` and Regex's `|`.
The `/` operator in PEG does not behaves like the `|` operator in Regex. They don't have the same semantics, looks similar, but they are different beasts.

**Comment by MegaArman** [comment]
Ok, thank you. I will just sort the literals for the time being, but I think it would be nice if the documentation made this more clear as it's sort of an unusual task to have to perform for literals.
