### ISSUE TITLE
Returning object literal with right bracket causes syntax error when generating parser

### ISSUE THREAD

**Issue by Qix-** [pegjs/pegjs#581]
```pegjs
foo
	= 'hello'
	{
		return {foo: '}', bar: ['}']};
	}
	;
```

Seems to be an issue when string literals contain `}` as changing the `'}'` to something different (e.g. `'a'`) causes the parser to successfully generate.

EDIT: confirmed that changing the above literals to `'\x7d'` (which equates to the right square bracket) fixes the issue and is a viable workaround.

Looks like the parser needs to be fixed (:

**Comment by pjmolina** [comment]
It is a well-known and documented limitation of pegjs. 
See #576, there you have the why and a workaroud.

**Comment by Qix-** [comment]
You're right, though this is really a duplicate of #89.
