### ISSUE TITLE
Ability to rely on external dependencies inside rule actions?

### ISSUE THREAD

**Issue by aptuslogic** [pegjs/pegjs#582]
I have a grammar with several rules that instantiate a class that I have defined in an external dependency.  However, because this dependency isn't known to pegjs itself, I get a "class not defined" error.  I know you can rely on stuff defined in an initializer block that precedes the first rule, but I'd like to do an import in that initializer.  Is that possible?  I'd like to do something like this in my grammar:

{
   import 'MyObject' from 'MyObject';
}

start = "abc" { return new MyObject() }

**Comment by futagoza** [comment]
Sure it is, but I suggest you use `require` instead unless you plan to transpile the generated parser for some reason 😆

**Comment by aptuslogic** [comment]
I can use require, but I'm not clear on how it gets used here.  This is all happening on the client side, so as far as I understand, require isn't available.  If I change my initializer block to:

{
   var MyObject = require ('MyObject.js');
}

then it tells me that require is not defined.

**Comment by futagoza** [comment]
What version of PEG.js are you using? `v0.10.0` or `v0.11.0-dev`?

On _v0.10.0_ you can use the `dependencies` option along with the `format` option (`commonjs`, `amd` and `umd`) to add require statements before the generated parser in the returned source.

From _v0.11.0_ (and currently with _v0.11.0-dev_) you can also use the `es` format to generate import statements instead. If you're using PEG.js v0.11 from the CLI, [using a config file](https://github.com/pegjs/pegjs/blob/master/docs/guides/command-line.md) will make this easier.

**Comment by aptuslogic** [comment]
I'm using v0.10.0.  I tried uninstalling and installing v0.11.0, but it's telling me no such version is available.

**Comment by aptuslogic** [comment]
Never mind, found it.   Installed v0.11.0-dev.325.  I'll try compiling the grammar and using these options and see how it goes.

**Comment by aptuslogic** [comment]
Awesome, I'm compiling the grammar and used the dependencies setting and es format in my config file, and it works perfectly.  Thank you very much!
