### ISSUE TITLE
\s is not recognized as a whitespace character in pegjs regular expressions

### ISSUE THREAD

**Issue by jonknowles** [pegjs/pegjs#584]
### Issue type

- **Bug Report:** 

### Prerequisites

- **Can you reproduce the issue?:**  yes
- **Did you search the repository issues?:**  yes
- **Did you check the forums?:**  yes
- **Did you perform a web search (google, yahoo, etc)?:**  yes

### Description

The regular expression '[\s]' does not match whitespace in pegjs, instead it matches the 's' character literally. I take it this in an intentional decision and not an oversight, but if so it seems like this should be noted prominently in the documentation, since it doesn't seem intuitive at all. 

### Steps to Reproduce

1. Go to https://pegjs.org/online
2. Replace the space with a \s in the whitespace regex so it looks like this: [\s\t\n\r]*
3. Replace every space in the input text with an 's' character, so it looks like this: 2s*s(3+s4)
4. Notice the input is parsed successfully. 

**Expected behavior:**

Match whitespace as defined [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions):

> Matches a white space character, including space, tab, form feed, line feed. Equivalent to [ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff].

**Actual behavior:**

Matches any 's' characters literally.

**Comment by futagoza** [comment]
😆 I remember a few years ago when I first used PEG.js I did the same thing.

PEG.js does not have JavaScript RegExps; What youre using is character classes (See [website](https://pegjs.org/documentation#grammar-syntax-and-semantics-parsing-expression-types) or [local doc](https://github.com/pegjs/pegjs/blob/master/docs/grammar/parsing-expression-types.md#characters))

**Comment by jonknowles** [comment]
If you made the same mistake yourself, shouldn't this be explicitly documented somewhere? Both of the sections you linked to are ambiguous.
