### ISSUE TITLE
Parsing expression1 @expression2 ... expressionn

### ISSUE THREAD

**Issue by nicolas-hili** [pegjs/pegjs#588]
### Issue type

- **Bug Report:** yes
- **Feature Request:** no 
- **Question:** yes
- **Not an issue:** no

### Prerequisites

- **Can you reproduce the issue?:** yes
- **Did you search the repository issues?:** yes 
- **Did you check the forums?:** yes
- **Did you perform a web search (google, yahoo, etc)?:** yes

### Description

It looks like it is impossible to use the "@" symbol within expressions as it is explained in [this page](https://github.com/pegjs/pegjs/blob/master/docs/grammar/parsing-expression-types.md#expression1-expression2---expressionn-1). I attempted to generate a parser from the example given in the [page above](https://github.com/pegjs/pegjs/blob/master/docs/grammar/parsing-expression-types.md#expression1-expression2---expressionn-1), as well as from the [PegJS grammar](https://github.com/pegjs/pegjs/blob/master/src/parser.pegjs) itself. In both cases, I got the following error:

> SyntaxError: Expected "!", "$", "&", "(", ".", "/", "/*", "//", ";", character class, code block, comment, end of line, identifier, literal, or whitespace but "@" found.

I tried both using the online editor and using Node.js. The same error happened. At first, I thought it was an experimental feature not yet available. However, it seems that the '@' symbol seems is used in the [PegJS grammar](https://github.com/pegjs/pegjs/blob/master/src/parser.pegjs) itself, so I found strange that I could not find any other opened issues mentioning it. 

### Steps to Reproduce

Using the [online editor](https://pegjs.org/online):
1. Open the [online editor](https://pegjs.org/online)
2. Enter the example code below

Or using Node.js:
1. Create a nodejs application
2. Copy & paste the second example below
3. `$  node myApp.js`

**Example code:**

Using the online editor (taken from [here](https://github.com/pegjs/pegjs/blob/master/docs/grammar/parsing-expression-types.md#expression1-expression2---expressionn-1)):
```pegjs
start = MultiPluck
      / SinglePluck

SinglePluck = "0"? @integer
MultiPluck = @integer "." @integer

integer = $[0-9]+
```

Or via Node.js:
```js
var peg = require("pegjs")

var parser = peg.generate(`
start = MultiPluck
      / SinglePluck

SinglePluck = "0"? @integer
MultiPluck = @integer "." @integer

integer = $[0-9]+
`);

var output = parser.parse("011"); // Should return "11"
```

**Expected behavior:**

The output of the example above should return `"11"`

**Actual behavior:**

Instead, the aforementioned error appears. Note that removing the "@" symbol in the examples above would work and would output `['0','11']`.

### Software

- **PEG.js:** 0.10.0
- **Node.js:** 11.1.0
- **NPM or Yarn:** 6.4.1
- **Browser:**  Firefox 63.0
- **OS:** Ubuntu 18.04 
- **Editor:** vim

**Comment by futagoza** [comment]
Hi @nicolas-hili, this isn't a bug, it's just that PEG.js v0.10.0 (the [latest npm release](https://www.npmjs.com/package/pegjs) and used in the [online editor](https://pegjs.org/online)) doesn't support the value plucking operator, that's why you are getting that error.

Until PEG.js v0.11.0 comes out (before 2019 hopefully 😆) you can try value plucking using:

- https://www.npmjs.com/package/pegjs/v/0.11.0-dev.325
- https://pegjs.org/development/try _(recomended, more up to date)_

**Comment by nicolas-hili** [comment]
Thanks @futagoza for your quick reply! I indeed failed to see the reference to the development version in the wiki. I tried 0.11.0 it does work with the '@' annotation, thanks :)

**Comment by polkovnikov-ph** [comment]
So this feature did go to production. I missed it so much. Thanks!
