### ISSUE TITLE
Example 'arithmetics.pegjs' doesn't work

### ISSUE THREAD

**Issue by tdkihrr** [pegjs/pegjs#589]
### Issue type

- **Question:** 

### Description

Example 'arithmetics.pegjs' doesn't work. When I used this one to generate .js, pegjs would show me error message.

### Steps to Reproduce

1. download 'arithmetics.pegjs' file
2. input `pegjs -o arithmetics-parser.js arithmetics.pegjs` in cli
3. it will show you '7:23: Expected "!", "$", "&", "(", ")", "*", "+", ".", "/", ":", "?", character class, code block, comment, end of line, identifier, literal, or whitespace but "@" found.'

**Expected behavior:**

It can generate arithmetics-parser.js.

**Actual behavior:**

It doesn't work.

### Software

- **PEG.js:**

**Comment by YemSalat** [comment]
Looks like the arithmetics example was broken by this update: https://github.com/pegjs/pegjs/commit/fd3dbb77ac7531f0d5b170d9bffbd7eff81a928d#diff-a331e28b2bcefde7c0a53ceb8a17727e

@futagoza can you please double check this? Is it only supposed to work in the newer version of pegjs?

**Comment by futagoza** [comment]
As @YemSalat found, the current example in the master branch only works with the upcoming 0.11 but if you want to see the working example for 0.10 it is here https://github.com/pegjs/pegjs/tree/v0.10.0/examples

**Comment by tdkihrr** [comment]
thx
