### ISSUE TITLE
Cannot install pegjs with node10+

### ISSUE THREAD

**Issue by BK-Choi** [pegjs/pegjs#595]
### Issue type

- **Bug Report:** yes
- **Feature Request:** no
- **Question:** no
- **Not an issue:** no

### Prerequisites

- **Can you reproduce the issue?:** yes
- **Did you search the repository issues?:** yes
- **Did you check the forums?:** no
- **Did you perform a web search (google, yahoo, etc)?:** yes

### Steps to Reproduce

1.  run `npm i pegjs`

**Example code:**

no need

**Expected behavior:**

pegjs installed without error

**Actual behavior:**

  ```sh
  /usr/local/Cellar/node@10/10.14.2/bin/node /usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto

  > agensgraph@0.1.0-rc prepack /Users/user/.npm/_cacache/tmp/git-clone-470df787
  > pegjs --output ./lib/agens.js --allowed-start-rules EdgeArray,VertexArray,_Edge,_Vertex,_Path,GraphId ./lib/agens.pegjs

  sh: pegjs: command not found
  Unhandled rejection Error: premature closeo lifecycle agensgraph@0.1.0-rc~prepack: agensgraph@0.1.0-rc
      at PassThrough.onclose (/usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
      at PassThrough.emit (events.js:187:15)
      at emitCloseNT (internal/streams/destroy.js:59:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)`
```

### Software

- **PEG.js:** 0.10.0
- **Node.js:** 8.14.1 works, 10.14.2 doesn't work, 11.5.0 doesn't work
- **NPM or Yarn:** NPM 6.4.1
- **Browser:** no need
- **OS:** MacOS 10.14.2
- **Editor:** bash

**Comment by futagoza** [comment]
Hmm, that's weird. I use Node 10.14.2 on my local machine and I'm not having any issues installing and running PEG.js 0.10.0

- Are you running this straight on bash?
- Are you installing PEG.js the same way for Node 8/10/11?
- Can you give the logs for Node 8 and Node 11 (as you have for Node 10)

**Comment by BK-Choi** [comment]
i am sorry, this is not an issue
agensgraph module uses pegjs which is installed globally.

i didn't know `npm i pegjs` installs `agensgraph` as well..
my project's package.json file contains pegjs and agensgraph dependency.

@futagoza 
closing this issue and thx for your sincere comment

- **Are you running this straight on bash?** 
  - yes, bash, zsh, or even windows command line tool
- **Are you installing PEG.js the same way for Node 8/10/11?**
  - absolutely the same way
- **Can you give the logs for Node 8 and Node 11 (as you have for Node 10)**
  - no need
