### ISSUE TITLE
"Comparision" rule is not matching

### ISSUE THREAD

**Issue by deostroll** [pegjs/pegjs#601]
### Issue type

- **Bug Report:** _no_
- **Feature Request:** _no_
- **Question:** _yes_
- **Not an issue:** _no_

### Prerequisites

- **Can you reproduce the issue?:** _yes_
- **Did you search the repository issues?:** _yes_
- **Did you check the forums?:** _yes_
- **Did you perform a web search (google, yahoo, etc)?:** _yes_

Source code: https://github.com/deostroll/feel/tree/traces
Grammar file: **grammar/feel.pegjs**
Executable file: **dummy.js**
Program output: https://gist.github.com/deostroll/027ea709b1506393974e2ab5358640ca

### Description

Unable to figure out why the **Comparison** rule is not matching. I have enabled tracing for my parser. The built-parser (with default tracing) is available in the above source code repository. The output of the program is the trace + some console.log which comes towards the end - that is the parser messages itself. It is linked above.

### Steps to Reproduce

1. Download repo, and, npm install (make sure of the correct branch)
2. Copy code from below to file **dummy.js**
3. Run `node dummy.js`

**Example code:**
```js

const feelFactory = require('./index');

const {feel} = feelFactory();

const exp = "date(\"2012-12-25\") – date(\"2012-12-24\") = duration(\"P1D\")"
// const exp = "(1) - 2"
const spacedString = ' '.repeat(exp.length);
// 
const parserOptions = {};
const payload = {
    
}
try{
    var ast = feel.parse(exp); //parser call
}
catch(excep) {
    console.log(excep.message);
    let errStatement = exp;
    console.log(exp);
    let pointer = [].slice.call(' '.repeat(exp.length));
    pointer[excep.location.start.offset] = '↑';
    pointer[excep.location.end.offset] = '↑';
    console.log(pointer.join(''))
    // pointer[excep.location.start.offset] = '|';
    // pointer[excep.location.end.offset] = '|';
    // // errStatement += pointer
    // console.log(pointer.join(''));
    return;
}


    ast.build(payload)
    .then(res => {
        console.log(res)
    })
    .catch(e => console.log(e));
```

**Expected behavior:**

Should have evaluated to true

**Actual behavior:**

Throws a parser exception.

### Software

- **PEG.js:** 0.10.0
- **Node.js:** v10.15.1
- **NPM:** 6.2.0
- **Browser:** chrome
- **OS:** windows
- **Editor:** vs code

**Comment by futagoza** [comment]
After fiddling with this for 30+ minutes I realised something was off with the _input_, not the _grammar_ 🤣 

```sh
$ node
> "–".charCodeAt(0)
8211
> "-".charCodeAt(0)
45
```

In other words, this:

```js
const exp = "date(\"2012-12-25\") – date(\"2012-12-24\") = duration(\"P1D\")"
```

should be this:

```js
const exp = "date(\"2012-12-25\") - date(\"2012-12-24\") = duration(\"P1D\")"
```

**Comment by deostroll** [comment]
![Please wait...I have to shoot myself first...](https://media.tenor.com/images/608390ce1f7ee165c1dcaf0d18e02e6f/tenor.gif)

Thanks a ton!!!
