### ISSUE TITLE
dependencies in package.json should be devDependencies

### ISSUE THREAD

**Issue by ibc** [pegjs/pegjs#605]
### Issue type

- **Bug Report:** _no_
- **Feature Request:** _no _
- **Question:** _no_
- **Not an issue:** _yes_

### Prerequisites

- **Can you reproduce the issue?:** _N/A_
- **Did you search the repository issues?:** _yes_
- **Did you check the forums?:** _yes_
- **Did you perform a web search (google, yahoo, etc)?:** _N/A_

### Description

[package.json](https://github.com/pegjs/pegjs/blob/master/package.json#L24) has:

```json
    "dependencies": {
        "codecov": "3.1.0",
        "eslint": "5.13.0",
        "eslint-config-futagozaryuu": "5.6.1",
        "eslint-plugin-vue": "5.1.0",
        "mocha": "5.2.0",
        "mocha-junit-reporter": "1.18.0",
        "mocha-multi-reporters": "1.1.7",
        "nyc": "13.2.0",
        "rimraf": "2.6.3",
        "vuepress": "^1.0.0-alpha.32"
    }
```

All those dependencies should be placed into `devDependencies` because none of them are needed for an external application that depends on `pegjs`.

**Comment by futagoza** [comment]
The `package.json` that is in the root of this repository is meant for development purposes only, _and never should be used by an external application_.

The one that is published (and should be used by an external application) is [packages/pegjs/package.json](https://github.com/pegjs/pegjs/blob/master/packages/pegjs/package.json)

**Comment by ibc** [comment]
Oh, clear. Thanks.
