### ISSUE TITLE
How do I call the rule name inside the action?

### ISSUE THREAD

**Issue by 18510047382** [pegjs/pegjs#610]
I want to call rule name within **expression { action }**, what should I do?

**Comment by Mingun** [comment]
In all `CodeBlock`s you have access to current parser by variable `parser` and current options by `options`.

**Comment by 18510047382** [comment]
> 在所有`CodeBlock`s中，您可以通过变量`parser`和当前选项访问当前解析器`options`。

Can you tell me more specific?

**Comment by 18510047382** [comment]
As you can see, it is not defined.
<img width="304" alt="屏幕快照 2019-04-30 下午1 09 15" src="https://user-images.githubusercontent.com/45157599/56941790-5129f680-6b49-11e9-84b2-5c3096329d9f.png">

**Comment by Mingun** [comment]
> Can you tell me more specific?

Just try this code in https://pegjs.org/online:
```js
start = '' { return [parser, options]; }
```
> As you can see, it is not defined.

You type `option` instead of `options`

**Comment by 18510047382** [comment]
Thanks! :) `options` are defined, but `parser` is still not defined.

**Comment by 18510047382** [comment]
`start = '' { return [parser, options]; }`
This code works fine at https://pegjs.org/online, but it is not working on my computer.
<img width="398" alt="屏幕快照 2019-04-30 下午4 35 30" src="https://user-images.githubusercontent.com/45157599/56949724-2d28de00-6b66-11e9-9e3d-d96548ffecd3.png">

**Comment by Mingun** [comment]
You need update you pegjs version. `parser` available from [0.9.0 release](https://github.com/pegjs/pegjs/releases/tag/v0.9.0):

> The parser object can now be accessed as `parser` in parser code.

Anyway, you always can access to parser via `options`:
```js
// Your JS code
let parser = ...;
let result = parser.parse(myInput, { parser });
//                                 ^^^^^^^^^^ options object
```

**Comment by 18510047382** [comment]
But, My pegjs version is 0.10.0. 😨

**Comment by balagge** [comment]
access to parser via variable `parser` has been removed in 0.10.0

https://github.com/pegjs/pegjs/releases/tag/v0.10.0
