### ISSUE TITLE
How to make greedy mode stop matching in expressions?

### ISSUE THREAD

**Issue by 18510047382** [pegjs/pegjs#611]
For example, greedy matches a number until it encounters other non-numeric characters, but does not include other non-numeric characters.

Please tell me how can I do this?

Thanks! :-)

**Comment by Mingun** [comment]
All repeat operators (`*`, `+`) in PEG is greedy.
```js
// Parses:
// 00000000000 -> 0
// 0000100 -> 100
// 0000g -> fail
num = n:$[0-9]+ { return parseInt(n, 10); };
```
