### ISSUE TITLE
How to write an except style grammar rule?

### ISSUE THREAD

**Issue by deostroll** [pegjs/pegjs#613]
For e.g. rule should match all characters except double quotes and _vertical spaces_. I tried the following:
```
_allowed_chars_ = character & ( !( '"'/ vertical_space ) );
```
I ran it against the input `"They're"`

It seems to be error when encountering the character `e`. Since `"` follows `e` in the input sequence. Hence the `_allowed_chars_` rule is failing. 

Full gist of grammar here: https://gist.github.com/deostroll/422405d894c3dedbffe8182f3f2bd826

**Comment by futagoza** [comment]
Use this instead:

```js
_allowed_chars_ = !( '"'/ vertical_space ) ch:character { return ch; };
```

1. Using `& ()` is saying you want the parser to optionally want this, not an except
2. The return is required otherwise you get `[undefined, ""]`

**Comment by deostroll** [comment]
thanks, I misunderstood how `!` works...
