### ISSUE TITLE
workaround for left recursion

### ISSUE THREAD

**Issue by deostroll** [pegjs/pegjs#614]
For a grammar rule like follows: 
```
expression = textual_expression;

textual_expression = literal 
  / function_invocation;

// lot of lines follows...(shortened for brevity)

function_invocation = expression parameters;

parameters = .
```

The function invocation is defined that way...While generating the parser it errors out stating possible infinite loop. Is there a workaround I can implement here? (There are several rules like this in specification I am implementing).

PS: [WIP grammar file](https://gist.github.com/deostroll/75e5c58a9673560683d82e04f9f921ac#file-left_recursion-pegjs)

**Comment by futagoza** [comment]
Change `textual_expression` and `function_invocation`, adding an adtitonal rule like so:
```js
textual_expression = primary_expression 
  / function_invocation;

primary_expression = literal;

function_invocation = primary_expression parameters;
```

**Comment by deostroll** [comment]
But, `function_invocation` is not `literal` followed by `parameters`. Its `expression` followed by `parameters`. The error I got earlier was something like below:

```
Possible infinite loop when parsing (left recursion: expression -> textual_expression -> function_invocation -> expression)
```

**Comment by futagoza** [comment]
You're getting the left recursion error because PEG.js sees that `function_invocation` starts with `expression` (that refers to `textual_expression`), but this rule defines `function_invocation` as a possible parsing path, which can cause an infinite loop, hence the left recursion error.

The grammar change which I suggested basically stops the error while also leaving you the option to update `textual_expression` (hence `expression`) without causing another possible left recursion error.

**Comment by deostroll** [comment]
Thanks for the suggestion. However, I am a bit confused. According to the specification *textual expression* is a lot more complex. 
```
2. textual expression =
	a. for expression | if expression | quantified expression |
	b. disjunction |
	c. conjunction |
	d. comparison |
	e. arithmetic expression |
	f. instance of |
	g. path expression | filter expression | function invocation |
	h. literal | simple positive unary test | name | "(" , textual expression , ")" ;
```
The grammar I wrote was WIP. Eventually I have to write stuff to meet the above rules. There is a precedence defined, which was why **literal** came before **function invocation**

How should I write **primary_expression** given the above facts?

PS: Complete specification grammar is linked to [here](https://gist.github.com/deostroll/75e5c58a9673560683d82e04f9f921ac#file-grammar-txt)

**Comment by futagoza** [comment]
I would suggest putting everything under 2-h in `primary_expression` (looking at the spec agian, a better name would be `left_expression` maybe?).

For a better example to follow, look at the following rules in [EdgeVerve/feel/src/feel.pegjs](https://github.com/EdgeVerve/feel/blob/master/src/feel.pegjs)

- [TextualExpression](https://github.com/EdgeVerve/feel/blob/master/src/feel.pegjs#L111)
- [TxtExpi](https://github.com/EdgeVerve/feel/blob/master/src/feel.pegjs#L133)
- [LeftExph](https://github.com/EdgeVerve/feel/blob/master/src/feel.pegjs#L462)
- [FunctionInvocation](https://github.com/EdgeVerve/feel/blob/master/src/feel.pegjs#L472)

Following the specs is great (makes for consistent software), but you have to fill in the little gaps that can crop up depending on the software you're using or anything left open for implementers of a spec.

**Comment by deostroll** [comment]
Thanks. I got an idea of what to do. However, the way that grammar was written was what inspired me to ask such a question in the first place. :)
