### ISSUE TITLE
Add ability to pass parameters

### ISSUE THREAD

**Issue by 18510047382** [pegjs/pegjs#617]
Can you add the ability that I can pass parameters to the rule?
Because I really need it! :)

**Comment by Mingun** [comment]
What kind of parameters you mean? You can use `options` in the action and predicate code as well as in initializer. If you mean template rules, that already tracked in #45

**Comment by 18510047382** [comment]
Yes, I mean "template rules", and I hope you can add this feature!

**Comment by futagoza** [comment]
Closing, as Mingun mention, duplicate of #45
