### ISSUE TITLE
Parsing to ES6 Module class

### ISSUE THREAD

**Issue by GreenImp** [pegjs/pegjs#627]
### Issue type

- **Question:**  Yes

### Prerequisites

- **Did you search the repository issues?:** Yes
- **Did you check the forums?:** Yes
- **Did you perform a web search (google, yahoo, etc)?:** Yes

### Description

I have several expression in a grammar that get parsed into objects, like so:

```js
SortingModifier
 = "s" dir:("a" / "d")? {
   return {
     type: 'sort',
     direction: dir || 'a',
   }
 }
```

But what I need to do is parse them into a class object that I have defined in an es6 module:

```js
SortingModifier
 = "s" dir:("a" / "d")? {
   return new SortingModifier(dir);
 }
```

And the class module being something like:

```js
// SortingModifier.js

class SortingModifier{
  ...
}

export default SortingModifier;
```

Unfortunately, I can't find a way of getting this to work, as I need to somehow add an `import` statement into the generated grammar. Otherwise, running the grammar complains that `SortingModifier` is undefined.

I've tried generating the grammar through the CLI, and through the JS API without any luck.
I've also tried passing through the module as a dependency, but it doesn't seem to work with ES6 modules.

This complains that the module doesn't exist:
```bash
pegjs --dependency SortingModifier grammar.pegjs
```

But using the full path like this:
```bash
pegjs --dependency '../../modifiers/SortingModifier' grammar.pegjs
```
Generates something like this, which is invalid:
```js
var ../../modifiers/SortingModifier = require("../../modifiers/SortingModifier");
```

Is there a way of getting this work? Does it work in the unreleased v0.11.0? I saw #423 which is similar, and looks to be going out in that release.

### Software

- **PEG.js:** v0.10.0
- **Node.js:** v12.12.0
- **NPM:** 6.11.3

I'm also using Rollup to compile everything.

**Comment by log4b0at** [comment]
```js
const fs = require('fs');
const pegjs = require('./pegjs/packages/pegjs'); // pegjs path
const grammar = fs.readFileSync("./grammar.pegjs").toString(); // input grammar
const parser = pegjs.generate(grammar, {output: "source", format:"umd"});
fs.writeFileSync("./parser.js", parser); // output parser file
```
Here is my code to generate my parser, notice {format:"umd"} i think this is what you searching for

**Comment by GreenImp** [comment]
Sorry, it's been a long time since I've been able to look back into this issue.

My problem is that UMD isn't compatible with ES modules. So trying to add one of my ES modules as a dependency tries to bring them in as a commonJS dependency using `require`.

What I might try to do is generate the file manually, in a similar way to how you're doing, but see if I can add some custom scripts around it, to generate it as an ES module, with my dependencies `import`ed in. Not sure if that'll work though

**Comment by GreenImp** [comment]
I've managed to work around this by creating the file and inserting `import` statements at the top of the file.
You need to make sure that PegJS exports as "bare", which is the default.

I'm doing something like this:

```js
import fs from 'fs';
import pegjs from 'pegjs';

const dir = './grammars/';
const filename = 'grammar.js';

// load the grammar as a string
const grammar = fs.readFileSync(`${dir}grammar.pegjs`).toString();

// generate the parser as "bare" - Not UMD, AMD etc.
const parser = pegjs.generate(grammar, {output: 'source'});

// build an output string that contains the import statements that the parser needs
// within the output string, define the parser as a variable and export it (so we have a parser module)
const output = `import moduleA from './ModuleA.js';
import ModuleB from './ModuleB.js';

const parser = ${parser};

export default parser`;

// finally write the output string to a file
fs.writeFileSync(`${dir}${filename}`, output);
```

The created file looks something like this:

```js
import moduleA from './ModuleA.js';
import ModuleB from './ModuleB.js';

const parser = /*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */
(function() {
  "use strict";

   ...

  return {
    SyntaxError: peg$SyntaxError,
    parse:       peg$parse
  };
})();

export default parser
```

It's a bit hacky, but it works.
