### ISSUE TITLE
https://pegjs.org/ 402 Payment Required

### ISSUE THREAD

**Issue by JakeTunaley** [pegjs/pegjs#629]
https://pegjs.org/ is currently giving a 402 Payment Required response, giving the following data:

```
402: PAYMENT_REQUIRED
Code: DEPLOYMENT_BLOCKED
ID: syd1:wvsch-1573774859608-bec06190691b
```

**Comment by futagoza** [comment]
Yeah sorry, I had switched the payment plan to the new free plan (has everything I need) 3 weeks ago, but since the last deployment was still running on their Now v1 platform it got blocked since I had already removed my payment details 😅. Sorted out now.
