### ISSUE TITLE
location() return unexpected value for 1+2+3

### ISSUE THREAD

**Issue by plantain-00** [pegjs/pegjs#630]
### Issue type

- **Bug Report:** yes
- **Feature Request:** no
- **Question:** yes
- **Not an issue:** no

### Prerequisites

- **Can you reproduce the issue?:** yes
- **Did you search the repository issues?:** yes
- **Did you check the forums?:** no
- **Did you perform a web search (google, yahoo, etc)?:** yes

### Steps to Reproduce

1.  open the online: https://pegjs.org/online
2.  fill the example code below to the grammar
3.  fill `1+2+3` to the input

**Example code:**

```js
  // An example of code related to this issue
Expression
  = head:Factor tail:(_ ("+" / "-") _ Factor)* {
      return tail.reduce(function(result, element) {
        if (element[1] === "+") {
          var loc = location()
          return {
            type: "binaryExpression",
            left: result,
            right: element[3],
            range: [loc.start.offset, loc.end.offset]
          };
        }
      }, head);
    }

Factor
  = "(" _ expr:Expression _ ")" { return expr; }
  / Integer

Integer "integer"
  = _ [0-9]+ { return parseInt(text(), 10); }

_ "whitespace"
  = [ \t\n\r]*
```

**Expected behavior:**

```js
{
   "type": "binaryExpression",
   "left": {
      "type": "binaryExpression",
      "left": 1,
      "right": 2,
      "range": [
         0,
         3 // <- here
      ]
   },
   "right": 3,
   "range": [
      0,
      5
   ]
}
```

**Actual behavior:**

```js
{
   "type": "binaryExpression",
   "left": {
      "type": "binaryExpression",
      "left": 1,
      "right": 2,
      "range": [
         0,
         5
      ]
   },
   "right": 3,
   "range": [
      0,
      5
   ]
}
```

### Software

- **PEG.js:** the online
- **Node.js:**  the online
- **NPM or Yarn:**  the online
- **Browser:** Chrome
- **OS:** mac 10.14.6
- **Editor:** the online

**Comment by futagoza** [comment]
Sorry, after labelling the issue and starting to write a reply, I thought a working example would be helpful, but after I was done, I went to have breakfast feeling satisfied with myself 🤣

That's not a bug, `location()` is working as intended; You're just calling it from a place where the range is already set because it's fully parsed the expression of the rule (e.g if the input was `1+2+3+4` the value on all `range` properties from `Expression` would be `[0, 7]`).

Here's a working example of your grammar (with correct ranges):

```js
Expression
  = head:LeftHandTerm tail:RightHandTerm* {
      return tail.reduce(function(result, element) {
        return {
          type: "BinaryExpression",
          // `result.value` is for `head` only, the rest are `BinaryExpression` ast
          left: result.value || result,
          operator: element.operator,
          right: element.value,
          range: [result.range[ 0 ], element.range[ 1 ]]
        };
      }, head);
    }

LeftHandTerm
  = _ exp:Factor {
      var loc = location()
      return {
        value: exp,
        range: [loc.start.offset, loc.end.offset]
      };
    }

RightHandTerm
  = _ operator:("+" / "-" / "*") _ exp:Factor {
      var loc = location()
      return {
        operator: operator,
        value: exp,
        range: [loc.start.offset, loc.end.offset]
      };
    }
  / LeftHandTerm

Factor
  = "(" _ expr:Expression _ ")" { return expr; }
  / Integer

Integer "integer"
  = [0-9]+ { return parseInt(text(), 10); }

_ "whitespace"
  = [ \t\n\r]*
```

__EDIT:__ updated grammar to work out of the box with the default input in the [online editor](https://pegjs.org/online)
