### ISSUE TITLE
How can I express something like "a list separate by"?

### ISSUE THREAD

**Issue by shrinktofit** [pegjs/pegjs#642]
For instance I want a list separate by white spaces. Now I'm doing so HACK:

```
point
  = (point_element white_space)* point_element

point_element
  = vertex_index
```

The returned parse result is not friendly --- It would be nice if it only returns an array.

**Comment by Mingun** [comment]
Duplicate of #30

**Comment by vsemozhetbyt** [comment]
You can use something like this example from the JSON grammar:

https://github.com/pegjs/pegjs/blob/b7b87ea8aeeaa1caf096e2da99fd95a971890ca1/examples/json.pegjs#L70-L81

**Comment by vsemozhetbyt** [comment]
Or maybe just like this:
```js
const pegResult = require('pegjs/')
  .generate(`
    list
      = list:(
          [a-z]
          ("," " "* element:[a-z] { return element; })*
        ) {return list.flat(); }
  `)
  .parse('a, b, c');

console.log(pegResult); // [ 'a', 'b', 'c' ]
```

**Comment by shrinktofit** [comment]
> You can use something like this example from the JSON grammar:
> 
> https://github.com/pegjs/pegjs/blob/b7b87ea8aeeaa1caf096e2da99fd95a971890ca1/examples/json.pegjs#L70-L81

Great.
