### ISSUE TITLE
[Question] Can you pass arbitrary objects into a compiled parser's state?

### ISSUE THREAD

**Issue by Chocrates** [pegjs/pegjs#644]
### Issue type

- [ ] **Bug Report:** 
- [ ] **Feature Request:** 
- [x] **Question:** 
- [ ] **Not an issue:** 

### Prerequisites

-  [x] **Can you reproduce the issue?:** 
-  [x] **Did you search the repository issues?:** 
- [ ] **Did you check the forums?:**
-  [x] **Did you perform a web search (google, yahoo, etc)?:** 

### Description

Are you able to pass an arbitrary object to the parser for use within the grammer?  

For instance,  I am using the parser to create a DSL to assert on the internal status of a large object.  
When developing the parser within your (great) online tool, I was able to have a block at the top of the parser with some sample data like so:
```
{
  var context = {
  "property1": "yes",
  "property2": {
      "property3": "four"
    }
  }
}
```

Now that I am porting this parser into an actual workflow, I am struggling to get this context set.  
What I have done so far is prepend the context onto the grammer and then compile the grammer.  
Ultimately I am curious if I can add this context to the parser after the fact, so that I can precompile the parser from the grammer in a build step and not need to do that at runtime.   
Example:  
```
  // context is a global in this case
  const grammer = fs.readFileSync('src/parser.pegjs', 'utf-8');
  const final_grammer = '{var context = ' + JSON.stringify(context) + grammer;
  const parser = pegjs.generate(final_grammer);
  console.log(parser.parse('property1 == yes');
```

Surprisingly to me this works.  Actual code here: https://github.com/Chocrates/stop-action-filter/blob/master/src/main.ts#L25

**Comment by Mingun** [comment]
You have access to `options` object, that you pass as second argument to the `parse` method.
```js
  // context is a global in this case
  const grammer = fs.readFileSync('src/parser.pegjs', 'utf-8');
  const parser = pegjs.generate(grammer);
  console.log(parser.parse('property1 == yes', { context });
```
In grammar use `options.context` to get access to `context` object.

**Comment by Chocrates** [comment]
Thank you @mingun!  I am going to close this.  
I think this is the doc that mentions it it in case others find it useful: https://github.com/pegjs/pegjs/blob/master/docs/guides/javascript-api.md
