### ISSUE TITLE
How to parse string without space?

### ISSUE THREAD

**Issue by crapthings** [pegjs/pegjs#647]
I couldn't find any example to parse string with out space.

because there's no space in Chinese or Japanese

```
用户名是一个单行文本 //usernameisatext
```

what i want is an result like

```js
{
  name: '用户名',
  type: '单行文本'
} // 是一个 is dropped

{
  name: 'username',
  type: 'text'
} // "isa" is dropped
```

```
some = char+ "isa" char+

char = [a-z]
```

![image](https://user-images.githubusercontent.com/1147704/80210868-1a58c480-8667-11ea-831f-ea22e13967d4.png)

https://stackoverflow.com/questions/61382281/how-to-parse-grammar-like-chinese-that-has-no-space-between-word-with-peg-js

**Comment by Mingun** [comment]
This is impossible if you can not somehow determine where one word is ended and another is begin

**Comment by crapthings** [comment]
so i should preprocess input text to add padding on keywords right?

**Comment by Mingun** [comment]
Right. Or change you grammar in that way, that it can match over predefined list of keywords, like:
```js
rule
  = 'keyword1'
  / 'keyword2'
  / ...
  / char+
  ;
char = [a-z]
```
