### ISSUE TITLE
Up-to-date JavaScript grammar

### ISSUE THREAD

**Issue by brettz9** [pegjs/pegjs#654]
### Issue type

- **Bug Report:**  no
- **Feature Request:**  yes
- **Question:** no
- **Not an issue:** no

### Prerequisites

- **Can you reproduce the issue?:** N/A
- **Did you search the repository issues?:** Yes
- **Did you check the forums?:**  Yes, if you mean Google groups.
- **Did you perform a web search (google, yahoo, etc)?:** Yes

### Description

Though it is just an example, I'd nevertheless be interested to see the JavaScript grammar kept up to date.

**Comment by YemSalat** [comment]
Modern days JS grammar is quite complicated, so I personally think that the older version suits better for example purposes. If you need to parse actual modern JS - you can just use an existing parser, e.g. `babel`

**Comment by brettz9** [comment]
It'd be helpful to me to have an up-to-date JS grammar in PegJS, but your logic is reasonable, so closing. Thanks!
