### ISSUE TITLE
Cannot use parseFloat inside grammar

### ISSUE THREAD

**Issue by mliebelt** [pegjs/pegjs#664]
### Issue type

- **Bug Report:** yes
- **Feature Request:** no
- **Question:** no
- **Not an issue:** no 

### Prerequisites

- **Can you reproduce the issue?:** yes
- **Did you search the repository issues?:** yes
- **Did you check the forums?:** yes
- **Did you perform a web search (google, yahoo, etc)?:** yes

### Description

I have a grammar that allows to read structured comments. Comments are inside brackets, and some of them have a known structure. I have reduced the grammar to the bare minimum:

* Read floats inside an `eval` comment.
* Read the rest as string inside any other comment.
* Comments start with `[%` followed by the command.
* After the command, the value is read (depending on the command).
* As result, an object is produced with key and value. For the special `eval`comment, I would like to get a float.

### Steps to Reproduce

1.  Go to the online version of pegjs: https://pegjs.org/online
2.  Insert there the grammar below on the left.
3.  Use as example string to read this: `[%eval 1.01] [%eva 1.01] [%foo any] [%bar 1.023]`

**Example code:**

```js
  // An example of code related to this issue
{
  function merge(array) {
    var ret = {}
   // return array
    array.forEach(function(json) {
      for (var key in json) {
        if (typeof json[key] == "string") ret[key] = ret[key] ? trimEnd(ret[key]) + " " + trimStart(json[key]) : json[key]
        if (Array.isArray(json[key])) ret[key] = ret[key] ? ret[key].concat(json[key]) : json[key]
      }
    })
    return ret
  }
  
  function trimStart(st) {
    if (typeof st !== "string") return st
    var r=/^\s+/
    return st.replace(r,'')
  }

  function trimEnd(st) {
    if (typeof st !== "string") return st
    var r=/\s+$/
    return st.replace(r,'')
  }

}

innerComment
  = ws bl "%eval" wsp ev:stringNoQuot ws br tail:(ic:innerComment { return ic })*
      { var ret = {};  ret["eval"] = parseFloat(ev); return merge([ret].concat(tail[0])) }
  / ws bl "%" ac:stringNoQuot wsp nbr:nbr+ br tail:(ic:innerComment { return ic })*
      { var ret = {}; ret[ac]= nbr.join(""); return merge([ret].concat(tail[0])) }

nbr
  = !br char:. { return char; }

bl = '['

br = ']'
  
ws "whitespace" = [ \t\n\r]*
wsp = [ \t\n\r]+

stringNoQuot
  = chars:[a-zA-Z0-9.]* { return chars.join(""); }

```

**Expected behavior:**

I would expect to get the following JSON as result:

```
{
   "eval": 1.01,
   "eva": "1.01",
   "foo": "any",
   "bar": "1.023"
}
```

**Actual behavior:**
I get only the last 3 values (that are strings), but not the float.

```
{
   "eva": "1.01",
   "foo": "any",
   "bar": "1.023"
}
```

I have no idea. I would have expected an error (cannot read, whatever), or that the key `eval` and the value `1.01` as float are available. But it looks like something is skipped inside the parser, and the parser continues to parse.

### Software

- **PEG.js:** Current version 0.10 (as the online version)
- **Node.js:** 15.8.0
- **NPM or Yarn:** 7.5.1
- **Browser:** Chromium current
- **OS:** Linux Ubuntu 20.x
- **Editor:** WebStorm or browser editor

**Comment by Mingun** [comment]
Check this in the standalone installation. Web site uses JS library to convert output JSON to text, which have bugs and hides some keys

**Comment by mliebelt** [comment]
I have the same grammar running locally, with a current setup (Node, npm, ...). I just wanted to explain what is the easiest way to reproduce it. So the setup locally is:

1. Call `node_modules/pegjs/bin/ ...` with the necessary parameters.
2. Have a test case to check that.

You can see the [complete grammar here](https://github.com/mliebelt/pgn-parser/blob/master/src/pgn-rules.pegjs), line 227 is the one where I would like to use `parseFloat`.
I have corresponding [test cases to it](https://github.com/mliebelt/pgn-parser/blob/master/test/test-pgn.js), line 340 starts one of them. I expect there a string, because I was not able to produce it with using `parseFloat`.

**Comment by nmain** [comment]
Your `merge` function silently discards numbers:
```
      for (var key in json) {
        if (typeof json[key] == "string")
          ...
        if (Array.isArray(json[key]))
          ...
      }
```
It takes no action when `typeof json[key] == "number"`.  When this is corrected you get the expected output.

**Comment by mliebelt** [comment]
Thank you a lot for taking the time, and thank's for the analysis. Yes, my fault, I have not checked the merge function. I will close that ticket therefore.
