### ISSUE TITLE
Documentation should describe all features of the grammar specification language (e.g., dollar sign "$", "text()")

### ISSUE THREAD

**Issue by maksverver** [pegjs/pegjs#674]
I looked at https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs and noticed there are several rules that include features which are not explained in the public documentation available at https://pegjs.org/documentation.

Example 1:

```
UnaryOperator
  = $DeleteToken
  / $VoidToken
  / $TypeofToken
  / "++"
  / "--"
  / $("+" !"=")
  / $("-" !"=")
  / "~"
  / "!"
```

What does the `$` prefix do?

Example 2:

```
DecimalLiteral
  = DecimalIntegerLiteral "." DecimalDigit* ExponentPart? {
      return { type: "Literal", value: parseFloat(text()) };
    }
```

What does the `text()` function do? From the context I infer it returns the matched text as a string, but the documentation doesn't describe that this is possible (it contains an example that explicitly joins the elements of an array), and it isn't clear if there are other similar helper functions.

The documentation should be updated to explicitly mention all features of the parser generator.

**Comment by maksverver** [comment]
Actually I was wrong; both of these features are mentioned in the documentation, but they're a little difficult to search for.

For the text() function:

> The code inside the action can also access the text matched by the expression using the `text` function.

It would be nice if the documentation contained an explicit example that includes `text()` so it's easier to find it by searching for `text(`.

Arguably it would also be useful to have a separate section that explicitly lists all built-in functions available (`text()` and `location()`; or are there more?), but since the information I was missing is technically there, I'll close the issue.

**Comment by hildjj** [comment]
We now have this live on the site at https://peggyjs.org/documentation.html#action-execution-environment

**Comment by maksverver** [comment]
Thanks Joe! That's very helpful.
